### ISSUE TITLE
[Site Request] iranian manga reader

### ISSUE THREAD

**Issue by Hamid1376** [inorichi/tachiyomi-extensions#101]
I work in an iranian  manga group  and we tranlate comic/manga for free.the problem is that  because of Religious reasons goverment suspend us/: we change domain every time but lost many of our readers. is there a way that we can publish our translates on Tachiyomi ?
there are some changes that need to be done,like language.
this is a sample site for test:
http://trinityreader.tk/

we will be very grateful if someone can do it for us, It's about three years of effort.

**Comment by null-dev** [comment]
Where are you hosting your website? Where are you registering your domain?
You can't exactly publish your manga on Tachiyomi since you need somewhere
to host it first but I can help you out a bit if you need somewhere to host
where your government can't suspend you.

**Comment by Hamid1376** [comment]
until yesterday in iran. we are moving site to a vps from germany .now they they can't suspend site anymore, but from what i heard they use filtering after suspending .it's like firewall of china.site is up and has no problem but in iran no one can access website. 
so do we need to take another server to host a manga reader on it for tachiyomi?
if this is all of it, i can prepare it fast.building a manga reader site is easy,but after that i don't know what should i do that our translates can be displayed on tachiyomi.

**Comment by null-dev** [comment]
Judging from your current site, I might be able to add your website into
Tachiyomi for you. It would be nice if you could add an API however, that
makes my job easier.

Is the website at http://trinityreader.tk/ hosted in Germany?

**Comment by Hamid1376** [comment]
No. this one is in canada. I use tk domains for test.is it possible to change domain later? if it's not, then please tell me and i buy another domain for it, tk domains are free and may some one else take it.
the site has been buit via my manga redder cms and it doesn't have an api option.Unfortunately i don't know anything about php coding, if it is needed i can send user and password of host for you.
I really appreciate your effort and sorry for bad english.

**Comment by j2ghz** [comment]
How long does it usually take them to block your site? When you move to another country they can start blocking domain names and ip addresses. It is not a problem to change domain name in extension, but users have to install the new version to get the update. Second possibility could be for the extension to get the current domain name from a site that isn't blocked (github?) on launch. I'm not sure how far they'd go to investigate.

A more permanent (but much harder) solution could be to not use HTTP for hosting, use something they'd be unlikely to look into (SFTP with the key being distributed with the extension?). The problem is you have to balance advertising the new solution to your users versus potentially notifying the censors.

There is not much more that can be done from your side. Users could use VPNs or Tor to bypass the blocking (https://www.howtogeek.com/167418/5-ways-to-bypass-internet-censorship-and-filtering/)

**Comment by Hamid1376** [comment]
10-12 days.
if we don't publish address of manga reader and block it in google search, they can't find it and so it won't be filtered.
using vpn is illegal and many people can't use it.

**Comment by Hamid1376** [comment]
design of trinityreader.tk is a little similar to Mangahere.
can't we use mangahere source with a little change?

**Comment by null-dev** [comment]
@Hamid1376 Hey, I've noticed your webpage is down. Have you moved URLs?
