### ISSUE TITLE
dmzj always show retry

### ISSUE THREAD

**Issue by RtYkk** [inorichi/tachiyomi-extensions#1064]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:dmzj always show retry when I want to read manga.
  Provide tachiyomi version as well as version of source the report is about
Tachiyomi r1463
 dmzj extension ver 1.0.4

Only a few people can't read. But others work properly.

Here's a video
Link:https://pan.baidu.com/s/1EO0bJ08KhH6ErP1SNeB4kA 
Password:V98X

**Comment by Toarbit** [comment]
I also encountered this problem and finally managed to fix it.

The reason is that dmzj changed the Referer of the image from "https://manhua.dmzj.com" to "http://www.dmzj.com/". So just replace the url in https://github.com/inorichi/tachiyomi-extensions/blob/9105f9aef8f1fda471735fe26eee96e1191ad0ca/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L268

Then build a new apk and install.

Seems work well.

**Comment by CarlosEsco** [comment]
@toarbit. If you open a pull request and update the build.gradle I will merge the fix

**Comment by RtYkk** [comment]
> I also encountered this problem and finally managed to fix it.
> 
> The reason is that dmzj changed the Referer of the image from "https://manhua.dmzj.com" to "http://www.dmzj.com/". So just replace the url in
> 
> [tachiyomi-extensions/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt](https://github.com/inorichi/tachiyomi-extensions/blob/9105f9aef8f1fda471735fe26eee96e1191ad0ca/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L268)
> 
> Line 268 in [9105f9a](/inorichi/tachiyomi-extensions/commit/9105f9aef8f1fda471735fe26eee96e1191ad0ca)
> 
>  = super.headersBuilder().add("Referer", "https://manhua.dmzj.com")!! 
> Then build a new apk and install.
> 
> Seems work well.

Thank you very much. I will have a try.

**Comment by CarlosEsco** [comment]
Fixed in latest
