### ISSUE TITLE
MangaDex thumbnail issue

### ISSUE THREAD

**Issue by MrAndre96** [inorichi/tachiyomi-extensions#1126]
When I search on MangaDex a lot of thumbnails won't load even if I enable the low res option. It will then only load once I click on the manga. Below is a image with the results I get:
[https://i.imgur.com/BcENodC.jpg](https://i.imgur.com/BcENodC.jpg)

I use MangaDex version: 1.2.57 and app version: r1505

**Comment by CarlosEsco** [comment]
So this is a known will no work around for now until they release a new api (also low res isnt an option anymore afaik).  Here is some details for you using that first broken one on you screen shot immortal invincible :
when you search or browse the url for thumbnail is 
https://mangadex.org/images/manga/37367.large.jpg?1558158560

to get the actual high quality image for the cover and not pull lq into the browse (because this causes pixelated thumbnails)  we clean up the url like so
https://mangadex.org/images/manga/37367.jpg

now the problem lies here.  For some reason mangadex will store thumbs as jpg but not always store the full size the same.  So the actual url is:
https://mangadex.org/images/manga/37367.png

90% of the time covers load  your screen shot seems to be an anomaly for amount in one screen with broken images.
