### ISSUE TITLE
Manga Plus by Shueisha - Thumbnail Bug.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#1143]
Extension Version: 1.2.2.

Issue: None of the thumbnails are loading for any of the manga for this extension source, neither in the catalogue, nor in the library.

![Screenshot_2019-05-28-22-45-49-015_eu kanade tachiyomi](https://user-images.githubusercontent.com/28984045/58497809-602cb480-819a-11e9-8d7b-e7a92d621f0c.png)

**Comment by metroid112** [comment]
I think it's related to #866 since Shueisha also hosts Spanish versions of the manga AFAIK which sometimes don't get properly loaded.

**Comment by MercerBoi** [comment]
I just checked out your issue, and yeah I've experienced that as well. Perhaps a webview solution can be implemented to bind the "No Spanish Content" setting from the website, with the app...

**Comment by alessandrojean** [comment]
This happens with the mangas in the library because all the images requires a key to access and a maximum time to view it. So in this case the time probably expired and the app can't display it anymore. I tried to find some way to access the images without this maximum time, but I haven't succeeded yet. When I figure out a way to do that, I can submit a update to fix it.

About the pictures not showing in the catalogue screen, I'll take a look and try to fix it.
