### ISSUE TITLE
Tapastic -> Tapas (rename extension)

### ISSUE THREAD

**Issue by superuser-does** [inorichi/tachiyomi-extensions#1165]
Arguably pedantic, but please investigate if _Tapastic_ can be renamed to _Tapas_ without of course causing any breakage. This might need additional functionality in the core app if it does indeed break things in any way.

They've used that name since 2017 and I can see at least one other person filed an issue due to difficulty finding the extension. I only just discovered the service myself and wasn't aware of its old name. It's worth making the change in the interests of usability if it isn't breaking or painful to implement a method.

**Comment by SnakeDoc83** [comment]
This can be closed.  Name was changed (as it appears in the extension list) in #1853.

**Comment by superuser-does** [comment]
It's not a full fix, but the maintainer is welcome to close if there is no other solution.

**Comment by SnakeDoc83** [comment]
My understanding is that changing the catalog name would change the
extension's source id which would mean that manga in your library would
have a different id than the extension; so your manga wouldn't receive
chapter updates any longer.  In order to continue receiving new chapters
for those manga in your library you'd have to migrate them.  In other words
you'd migrate your manga from Tapastic to Tapas even though it's the same
extension you'd be using.  I don't think this would be an obvious step to
most users or all that convenient.
