### ISSUE TITLE
[Source request] [English] GetManhwa

### ISSUE THREAD

**Issue by AiEsper** [inorichi/tachiyomi-extensions#1237]
After manhwahentai dying, please add GetManhwa.com

**Comment by waptik** [comment]
> @waptik Bro can you please work on this?

Sure, i don't mind. But it'll take some time as i have other requests(3) pilled up.

**Comment by joseph619** [comment]
@SnakeDoc83 Isn't this similar to all other Madara extension?

**Comment by SnakeDoc83** [comment]
No, it may have been at one point and it is possible to find the occasional page that uses it, but on the whole it's something else.

**Comment by joseph619** [comment]
I see. Does this one use Madara?

https://github.com/inorichi/tachiyomi-extensions/issues/1231

**Comment by SnakeDoc83** [comment]
Toonily still does.

**Comment by joseph619** [comment]
I see. Shouldn't Toonily be moved to Madara then? I know it was supposed to be done quite some time ago but was never finished.

**Comment by SnakeDoc83** [comment]
I mentioned that when someone opened an issue about fixing its filters or whatever the issue was recently.  Ideally it should be in Madara, but since it's currently working I'm not sure it "should" be moved.  In other words, moving it would be fine but not moving it isn't exactly terrible.  If it breaks again or someone wanted to make changes, then I'd say it "should" be moved.  That's all semantics and my opinion though, others might feel more strongly that sources should be condensed whenever possible regardless of what state their extension is in.

**Comment by joseph619** [comment]
I think all similar sources should always be group together for consistency.
