### ISSUE TITLE
[Source Request] Crunchyroll Manga (If not for reading, for progress syncing)

### ISSUE THREAD

**Issue by starg09** [inorichi/tachiyomi-extensions#1250]
Link to their frontpage: https://www.crunchyroll.com/comics/manga

Even if not shown in the top bar for every language, most of the content seems to be available in most, if not all, regions CR works on. There's the issue of some chapters only being accesible by non-premium users, and also the potential difficulties accesing the content within the app (no real idea on this myself).

My thought on submitting this suggestion, though, was more on the "having all sources in one app" sense. Not sure if possible, but even if the reader redirected to the website (or the [official CR manga app](https://play.google.com/store/apps/details?id=com.crunchyroll.crmanga&hl=es_AR)) that'd already be nice; mostly due to being able to easily sync to MAL/AL/etc.

Would this be implementable at all? Thanks for reading.

**Comment by arkon** [comment]
The legality of this is questionable enough that it'd deter me from wanting to implement it. They also don't have an API and aren't really designed for syncing outside of CR itself, so I'll have to say no to that as well.

**Comment by zekiz774** [comment]
Crunchyroll does have an API. With a quick google search you can find a documentation.

**Comment by E3FxGaming** [comment]
Crunchyroll does not have an OFFICIAL API.

That being said the initial request and response were made when most users still had to use the crappy flash player for reading manga on Crunchyroll. Hence an API was necessary if you wanted to get data.

With Adobe not supporting Flash Player anymore since the end of 2020, Crunchyroll migrated all users to a HTML 5 based manga reader mid December 2020.

Maybe this request could be looked at again since an API isn't needed anymore -> web-scraping could be possible and wouldn't be that different from what extensions do with other websites.

**Comment by CarlosEsco** [comment]
I'm confused if you are using crunchyrolll as a tracker why are you not just using their app?

**Comment by zekiz774** [comment]
Oh. Now I understand. Crunchyroll has an official API: api.cruchyroll.com 
but I don't know if it's still working.

Also, I don't use Crunchyrolls app, because it's ugly and I don't like the reader.
