### ISSUE TITLE
ManaMoa (MangaShow.Me) not working

### ISSUE THREAD

**Issue by moodyrunner** [inorichi/tachiyomi-extensions#1277]
ManaMoa (MangaShow.Me) extension number 1.2.12
tachiyomi version 0.8.4

The extension recieves a 503 error when browsing or searching for a manga. However, The website functions normally.

**Comment by SnakeDoc83** [comment]
Probably a website issue.  You say the website worked for you, but it's down right now when I checked; so maybe it's been sporadically down the last few hours.  Wel'll have to wait for it to come back up in any case.

**Comment by moodyrunner** [comment]
Are you sure you're looking at the correct website? I just checked manamoa.net right now and the extension still doesn't work.

**Comment by SnakeDoc83** [comment]
There's a good chance I tried http://mangashow.me instead of looking at what's in the code.  Looking at the code, the extension is using manamoa3.net.  Cloudflare could be the issue, visiting that site I get cloudflare's "checking your browser before accessing" page before the actual site loads.

There seems to be a number of the manamoa sites (manamoa.net, manamoa4.net, manamoa10.net) and they all have the same content.  Switching the extension's url to one that isn't interrupted by cloudflare seems to fix things.  That may not be an ideal solution though.

**Comment by moodyrunner** [comment]
Ah, i see. Thanks!

**Comment by animefreakdaf** [comment]
I've tried using those three links you've given as the extension url but all I get is an "unexpected url" error.

**Comment by DitFranXX** [comment]
It seems there's issue that Image descrambler(which uses http header) with a new cloudflare challenge solver (which released with 0.8.4). 
When site has a CF 'wait up to 5 seconds' like challenge has been enabled, browse is unavailable with error.

I will fix this issue soon as possible(maybe in a week)
Sorry about unmaintaining extension works due to work long time.
Temporary workaround is using override URL to challenge disabled domain.

@animefreakdaf I think you just entered domain. You should enter like this: `https://manamoa8.net`. I will improve this when I fix this problem

**Comment by SnakeDoc83** [comment]
[This](https://twitter.com/manamoa20) Twitter account seems to tweet the current domain out whenever it changes; they're currently on manamoa12.net.  The descrambler is fine I think, I was playing around a little last weekend and it works with manamoa12.net, but I kind of dislike the idea of updating every 2-4 weeks just to change the URL so I was trying to think of a more permanent solution.  While it's fairly straightforward getting the new URL programmatically, I don't know how to assign it to the baseUrl val.

**Comment by DitFranXX** [comment]
@SnakeDoc83 Actually, Image descrambler itself is not problem. On cloudflare interceptor, it sends a not-normal header, Descrambling Information headers (that handles on interceptor). Which causes CF Challenge failure (when CF challenge occured).

And also I don't like add something like 'Retrive url'. Since This is one of provider extension and not for site-exclusive *app*, It should be a simple as possible. I would more like to add that Twitter url in the app.

**Comment by moodyrunner** [comment]
> 
> 
> It seems there's issue that Image descrambler(which uses http header) with a new cloudflare challenge solver (which released with 0.8.4).
> When site has a CF 'wait up to 5 seconds' like challenge has been enabled, browse is unavailable with error.
> 
> I will fix this issue soon as possible(maybe in a week)
> Sorry about unmaintaining extension works due to work long time.
> Temporary workaround is using override URL to challenge disabled domain.
> 
> @animefreakdaf I think you just entered domain. You should enter like this: `https://manamoa8.net`. I will improve this when I fix this problem

thanks!
