### ISSUE TITLE
[ISSUE]Unionmangas.top HTTP 503 error

### ISSUE THREAD

**Issue by otavioalbucosta** [inorichi/tachiyomi-extensions#1324]
https://unionmangas.top/ now redirects to https://unionmangas.top/novo
I think that some URL changed on the site update
I can't send a pull request because i'm not with a PC right now :/

**Comment by SnakeDoc83** [comment]
The extension is fine I think, even with the redirect.  They've enabled capthcas though; so open a manga in webview, solve the captcha, and see if the extension works (it should).

**Comment by alessandrojean** [comment]
I'll take a look today, as the extension need some improvements too.

**Comment by otavioalbucosta** [comment]
Well, when I open the manga in web view, it works fine, even with the redirect, but it shows no captcha to me, and the manga viewer still get the 503 HTTP error
Honestly I have no idea about where the error is, but thanks for the help!

**Comment by alessandrojean** [comment]
I am trying to take a look right now, but it may take a while since apparently the site is offline right now. This probably is the reason you're getting the HTTP 5xx errors. When the site is online again, I will take a look and rewrite some parts of the code.

**Comment by otavioalbucosta** [comment]
That's really strange, when i get the error I immediately check the source site and it works fine on my browser or even in the web view, but the extension still gets the HTTP error. Some time later I check and the extension works perfectly fine, it's like sometimes the server refuse the request made by the extension, but I really have no idea if that occurs because of the source server or the Tachiyomi extension. Right now it is working fine, but sometimes I get the error again

**Comment by alessandrojean** [comment]
Well, in my PC the site doesn't load, it's locked in [this screen](https://imgur.com/BaJ8WmQ). Same on the browser and in Tachiyomi on my phone. If you open the DevTools console in Chrome, you can see the HTTP 503 error [too](https://imgur.com/lZVdd55). Maybe the site is unavailable for some regions, since they use Cloudfare now, or they are doing some kind of maintenance. I'll have to wait if they fix it this problem before changing something in the extension.

For now, what I can recommend you is to temporarily migrate your mangas to another source, like MangasProject (that contains the MangaLivre too), or MangaHost.
