### ISSUE TITLE
Chapter komikcast not load

### ISSUE THREAD

**Issue by hostkit** [inorichi/tachiyomi-extensions#1438]
Extension
Name: komikcast
Version: 1.2.3

Some chapter not load, only button try.
Connection normally, another chapter same manga load normally. I dont know its happened.

Read another source showing normally

**Comment by rama982** [comment]
Img url is find but tachiyomi can't load it.
https://github.com/inorichi/tachiyomi/issues/2148

**Comment by SnakeDoc83** [comment]
@hostkit Which manga and chapter?

**Comment by rama982** [comment]
> @hostkit Which manga and chapter?

see manga Taishou Otome Otogibanashi with latest chapter

**Comment by SnakeDoc83** [comment]
@rama982 
The images are broken when I try to load 38.2 on my PC.  Same thing with Maid Manga.  Double check your webview, because when I tried viewing 38.2 by webview only [this ](https://2.bp.blogspot.com/-cAknF4HjpHg/XChG9Rs3G2I/AAAAAAAAScY/xqZEmdOXqy4UOLwekfKG0l2SqdecA38CACLcBGAs/s1600/iklan.png) image loaded, not the actual manga images.

**Comment by rama982** [comment]
@SnakeDoc83 cant see on tachiyomi webview because site popup, but i test on android browser images is fine.
On PC i tried using Chrome based browseer its fine too, but image broken on Firefox.

**Comment by SnakeDoc83** [comment]
Weird, doesn't work for me on Android's browser or Chrome.

**Comment by arifr007** [comment]
i've try adding some header to load image from i0.wp.com https://github.com/inorichi/tachiyomi-extensions/pull/1574
