### ISSUE TITLE
[French] JapScan

### ISSUE THREAD

**Issue by pichu66** [inorichi/tachiyomi-extensions#146]
French site request: JapScan

Thanks for your amazing job!

**Comment by cmalard** [comment]
http://www.japscan.cc/mangas/

**Comment by AmineI** [comment]
That one is being used by another app (MangaMaster) which I find a bit questionable though. I'll try to see how they get that source, must be feasible if they do it.

**Comment by CarlosEsco** [comment]
Such a weird source no search or covers on manga page

**Comment by arkon** [comment]
I guess since you have the entire list of manga already, you could implement a local search. Not much you can do about the thumbnails, unfortunately.

**Comment by G4bleb** [comment]
The 3 functions i have to use are : 
- searchMangaRequest(), which has access to the query, and returns a webpage
- searchMangaSelector(), which contains the css selector to the element containing a manga
- searchMangaFromElement(), which looks for the data of the manga inside the element (title and url)

These functions are defined between line 61 and 74 of Japscan.kt in my commit.
Those are overrides of parent functions, so I can't change their input/output behavior.

I suppose the function where a search could be done would be searchMangaRequest(), because it has access to the query, but it returns a webpage, and because of that, I could not think of a way of making the search work.
Maybe one could edit the contents of the webpage so It only contains matching mangas, but I do not know if that is possible.

**Comment by AmineI** [comment]
Yeah a weird source it is. I don't know if tachiyomi supports that (I can also foresee tracking issues with that ?), but some mangas only have volumes instead of chapters ( ex : Iris Zero https://www.japscan.cc/lecture-en-ligne/iris-zero/volume-1/ ) while One Piece have chapters ( as expected I believe)

**Comment by G4bleb** [comment]
Volumes are just handled like chapters : for example with hunter x hunter :
![screenshot_20180902-152717](https://user-images.githubusercontent.com/14895661/44956454-075b1480-aec5-11e8-840d-6129a03f356b.jpg)

**Comment by AmineI** [comment]
Just checked, and there are indeed tracking issues : Reading a complete volume is tracked on Anilist and others as a single chapter. Not like there was much we could do about it right now but well :  Manual tracking needed in that case :)
