### ISSUE TITLE
Issue with Heaven Manga extension

### ISSUE THREAD

**Issue by MrJtowN** [inorichi/tachiyomi-extensions#1461]
Certain mangas within the Heaven Manga extension won't have their chapters tab load up. They'll instead get a grey bubble at the bottom stating, Unparseable date: ""

Examples of such mangas are: Argate Online, Builder, Goblin Slayer, and Onepunch-Man, among others.

Tachiyomi v0.8.4, Heaven Manga English v1.2.2

**Comment by SnakeDoc83** [comment]
I've opened a PR to update the extension, but as a heads up to you some of the chapters on their website are broken (no images) so you may want to use a different source depending on what chapter you're on with the manga you've mentioned.

**Comment by MrJtowN** [comment]
> I've opened a PR to update the extension, but as a heads up to you some of the chapters on their website are broken (no images) so you may want to use a different source depending on what chapter you're on with the manga you've mentioned.

Do you recommend another manga source like Mangadex?

**Comment by SnakeDoc83** [comment]
I think it's best to use multiple extensions.  As good as any one might be,
none will be absolutely perfect whether due to not having a manga you want,
missing chapters, or they don't update fast enough for your liking.

That said, MangaDex and Mangasee are the 2 large sources I prefer.  Both
are solid sources and between them you'll probably find most of what you
want.  If you're looking for webtoons, get the Madara extension which has
multiple sources and some of them are good for that.  There's also the
Holymanga extension which is basically the same as Heavenmanga.

Beyond that, try some other extensions too, see if they provide you any
benefits.

**Comment by pavan3999** [comment]
![Screenshot_20191002-130134](https://user-images.githubusercontent.com/23577468/66026054-934ece00-e515-11e9-85fd-c0173109928a.jpg)
same in latest holymanga & heaven manga extension
