### ISSUE TITLE
[SOURCE REQUEST] Wowe Scans (Genkan) 

### ISSUE THREAD

**Issue by tblader** [inorichi/tachiyomi-extensions#1491]
https://wowescans.co/home

**Comment by bbtora** [comment]
@SnakeDoc83 for Genkan maintenance.

**Comment by SnakeDoc83** [comment]
I found them yesterday too, was going to hold off adding them because it looked like they weren't done uploading.  I've checked again and their state isn't too bad.  A Returner's Magic Should Be Special shows as having 70 chapters but there's only 11 uploaded and Sweet X Trouble doesn't have any chapters.  I'll add them but keep this in mind once they're added and you're browsing their catalog.
