### ISSUE TITLE
KOMGA SLOWING DOWN CATALOGUE SEARCH

### ISSUE THREAD

**Issue by shinh28** [inorichi/tachiyomi-extensions#1592]
Just like what the title says, komga slowed down catalogue searching for me. When I still had it installed searching would take longer than usual, but once it was gone, the search became fast again just like the way it did. Just want y'all to know. I'm using the latest version of tachiyomi.

**Comment by arkon** [comment]
Was your Komga instance running at the time?

**Comment by gotson** [comment]
@shinh28 if you have more details on this issue i am interested, being the developer of Komga and its Tachiyomi extension.

- Did you had a Komga server configured in the extension ?
- Was the server running at the time ?
- Did you try searching in Komga only, and not from the catalogue view ?

If no server is setup or if the server is unreachable, the search method for Komga in Tachiyomi will throw an exception straight away.

I don't know exactly how the catalogue search is done, it may be slow because of the exception.

I tried it on my side, with an unreachable and reachable Komga server, and the Komga search is always the fastest, compared to other extensions.

**Comment by SnakeDoc83** [comment]
@arkon This can be closed.  Tachi handles global search better in .8.5; so if Komga really was slowing down search in .8.4 it shouldn't be as much of a hindrance now.  Plus, gotson's made some changes since then to the extension.
