### ISSUE TITLE
Heaven Manga and Holy manga Exhausted Prematurely (again)

### ISSUE THREAD

**Issue by kutuu21** [inorichi/tachiyomi-extensions#1613]
I'm using  tachiyomi v.0.8.4  and Holymanga & Heavenmanga extension v.1.2.2

After i report issue about Heaven Manga extension a few days ago (#1575), i uninstall **_Heaven Manga extension v.1.2.3_** and then i install **_Holymanga & Heavenmanga extension v.1.2.2._**
when i try open any manga chapters in  Holymanga  or Heavenmanga Catalogues, , i always get "Source Exhausted Prematurely" error (again), but when i try to "open in browser" or "open in web view" and  its working fine. Sometimes when i try to open Holy manga  or Heaven manga Catalogues it won't showed any manga. 

![20191004_164733](https://user-images.githubusercontent.com/55904603/66200477-5d534a80-e6cb-11e9-86d5-c0abbf92371b.jpg)
![uPqWiLW4](https://user-images.githubusercontent.com/55904603/66200479-5d534a80-e6cb-11e9-91df-f5de453ba135.jpg)

**Comment by joseph619** [comment]
@SnakeDoc83

**Comment by SnakeDoc83** [comment]
I'd hoped changing the baseUrls would have helped, but it seems not.  Some googling makes it seem like this is usually an issue with a server not being set up properly, but then shouldn't others be having this issue as well?  It hasn't happened to me.  I can try adding some headers, maybe change a request to cut down on some of the forwarding these sites do, but I can't be sure it'll help since I don't have this issue.

Out of curiousity, @kutuu21, are you using a VPN, browsing by Wi-Fi, or is there anything unusual about your setup?

Interestingly, this was an issue with Tachi in the past: https://github.com/inorichi/tachiyomi/issues/898

**Comment by kutuu21** [comment]
@SnakeDoc83 when i get that error, i'm using wifi (without VPN). But i tried using wifi with VPN and mobile data (with and without VPN) and the result still the same, i still get "Source Exhausted Prematurely" error.
I'm using Samsung Galaxy S9, Android 9 (Pie) (non root)

**Comment by ruuno123** [comment]
Can someone give link about holy manga?
