### ISSUE TITLE
[Bug] Mangaplus : Application crash

### ISSUE THREAD

**Issue by asimovitsch** [inorichi/tachiyomi-extensions#1678]
### Device information
* Tachiyomi extension version: 1.2.2
* Tachiyomi version: 0.8.4
* Android version: 4.4.4

## Steps to reproduce
1. Search for new chapters to any manga that has Mangaplus by Shueisha as its source (at least Act-Age)

### Expected behavior
If a new chapter is indeed available, show it. If not, stop the search and go on as usual

### Actual behavior
The main Tachiyomi app crashes

### Other details
I reverted to mangaplus extension version 1.2.1, and the app isn't crashing anymore upon checking for new chapters to manga on Mangaplus (but I imagine there are some downsides to it that I don't know of, given that you guys pushed an update to it). I know that this is not the most helpful bug report in terms of amount of detail, so I would really be thankful if others more tech-savvy tried to reproduce the bug.

**Comment by MerradOklom** [comment]
As I explained in the Discord server, this may be something related to the Android version, this happened to me too on my Android KitKat (4.4.2). I say this because for most people it seems to be working fine.

**Comment by alessandrojean** [comment]
What I can do to try to prevent that is check if the Android version is lower than Lollipop. If true, use the old method of parsing their API. But until that, the old version (1.2.1) should work fine for this cases.

Maybe this won't happen when the Kotlin version gets updated in the main app.

**Comment by alessandrojean** [comment]
The app crashes because this exception happens.

![Screenshot_20191023_132132](https://user-images.githubusercontent.com/14254807/67413758-27053e80-f598-11e9-8ebb-71c823ca6e5d.png)

It's related to the implementation of the Kotlinx Serialization lib being used (same as Kotlin version, 1.3.21), and by what I have been searching, may be related to the Android version and I don't really know if this can be fixed within the lib. We will have to wait to the main app and this repository gets the Kotlin updated, to see if the more recent versions of the lib still have this issue. Meanwhile, I will try to do some workaround to prevent that.
