### ISSUE TITLE
[Bug] MangaPlus by Shueisha : Infinite Loading

### ISSUE THREAD

**Issue by SaruDesu** [inorichi/tachiyomi-extensions#1697]
### Device information
* Tachiyomi extension version: 1.2.2
* Tachiyomi version: r1524
* Android version: 6.0.1

### Details
* When I was updating my libraries I noticed a Manga from MangaPlus was stucked.
* I checked the MangaPlus catalogue. The list is just loading not showing any manga. So I tried to downgrade it to 1.2.1 and it was fixed.
* Updated it again and the problem persisted.

**Comment by SaruDesu** [comment]
I saw another issue wherein using the Mangaplus leads to crashing of Tachiyomi, but in my case it does not.

**Comment by MerradOklom** [comment]
Just linking because they're related: #1678
So, apparently it crashes only on phones with KitKat and older, but it stucks for Lollipop and up? @alessandrojean maybe this can help you to aisle the cause

**Comment by alessandrojean** [comment]
Just to check it before I do anything: did you try to clear the cache and the database and see if it works?

**Comment by alessandrojean** [comment]
@SaruDesu, I tried to reproduce the behavior in a physical Android 6.0.1 device and in the emulator, but I couldn't reproduce it, it does not get stuck loading. Maybe it's something related to the cache or database; or some bug with the Kotlinx Serialization version, as it's not the current one; or something related specifically to your device. Since I can't reproduce, unfortunately I don't know how to fix :(

**Comment by SaruDesu** [comment]
> Just to check it before I do anything: did you try to clear the cache and the database and see if it works?
I did not try to clear the cache and the database.. Because the first thing I thought was to downgrade it. Now, I will try it

**Comment by SaruDesu** [comment]
Ok. So I tried to update it again to use the 1.2.2 version today and it worked.. I don't know why it was not loading but i would want to know..
