### ISSUE TITLE
[Bug] TuMangaOnline : Page list is empty 

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#1745]
### Device information
* Tachiyomi extension version: 1.2.11
* Tachiyomi version: r1532
* Android version: 4.4.2

## Steps to reproduce
1. Open manga
2. Select a chapter

### Expected behavior
Pages load

### Actual behavior
"Page list is empty" pop up

### Other details
Looks like they changed something in their reader, not sure.

**Comment by happywillow0** [comment]
I just checked several mangas from browse and latest and they loaded fine after I solved the initial captcha. 

There is the heavy captcha protection in addition to a rate limit. 

Is there any examples of mangas not loading?

**Comment by MerradOklom** [comment]
@happywillow0 it's fixed now. I did check before opening the issue if there was a captcha (which is something usual, but it gives errors like 403/404 when it's related to that). Anyway, I'll close the issue for the moment.

**Comment by happywillow0** [comment]
Even I have been temp banned for doing something on there before.

**Comment by MerradOklom** [comment]
Yup. I have seen reports in their forum of people getting banned for just reading on a desktop browser. Sadly there are not many scanlator-based sites, the only ones that I know are TuMangaOnline and Kumanga.

**Comment by MerradOklom** [comment]
This is happening again, here is a video I recorded on a different phone:
https://bit.ly/2oSKX1G
Maybe they're messing with the site?

**Comment by happywillow0** [comment]
I have managed to follow how things are going on to the extent of knowing why it is not working but not enough to fix anything. Two things:

Issue with webview: Using webview to figure out why it wasn't working doesn't work because they are using a redirect to go from the manga / chapters to the reader / pages. A modern browser follows the redirect but webview didn't so you see the forbidden message. 

Now on to the hard part. Based on the current code of the extension, the images used to be loaded directly on the reader website which is the way we like it. It means getting the urls of the images is easy. TMO is now using javascript to load the images in the reader so the initial page load doesn't actually contain any of the images itself. 

Here is the function:
```
function e(e, k, j) {
    var http = new XMLHttpRequest();
    var url = "/upload_images/" + e + '/' + k + '/' + j;
    http.open('POST', url, true);
    http.setRequestHeader('Content-type', 'application/json; charset=utf-8');
    http.setRequestHeader('X-CSRF-TOKEN', document.querySelector('meta[name="csrf-token"]').getAttribute('content'));
    http.onreadystatechange = function() {
        if (http.readyState == 4 && http.status == 200) {
            var elements = Object.values(JSON.parse(http.responseText));
            elements.forEach(function(element) {
                var imageDiv = document.createElement('div');
                imageDiv.classList = "viewer-image-container text-center";
                var imageElement = document.createElement('img');
                imageElement.classList.add('viewer-image');
                imageElement.src = imageRoute.replace(":IMAGE_NAME", element);
                imageElement.setAttribute("oncontextmenu", "return false;");
                imageDiv.appendChild(imageElement);
                document.querySelector("#viewer-container").appendChild(imageDiv);
            });
        }
    }
    http.send();
}
```
Somewhere, a JSON can be obtained which contains the list of img urls but I'm not sure where to post just yet.

**Comment by happywillow0** [comment]
This was working when I submitted the PR but I'm out and it isn't working again. I'll take a look when I get home.
