### ISSUE TITLE
[Bug] ManHuaGui : no chapters found

### ISSUE THREAD

**Issue by musouking** [inorichi/tachiyomi-extensions#1759]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: 0.8.4
* Android version: 9

## 
For some 18+ comics (for example https://www.manhuagui.com/comic/1011/) can be searched but error no chapters found.
On the website you need to click the confirm button to watch for the first time.

**Comment by happywillow0** [comment]
To add some more background onto this, there is a adult check that runs on javascript. The chapter list is hidden as a compressed base64 string. When the button is clicked, the string goes though `var n = LZString.decompressFromBase64($("#__VIEWSTATE").val());` so in order to read these chapters, we need to interpret the java script library of lz-string or something like that.

**Comment by rrprrp** [comment]
some manga only show in moblie device

https://www.manhuadui.com/manhua/wudengfendehuajia/443321.html (miss chapters)
https://m.manhuadui.com/manhua/wudengfendehuajia/443321.html (ok)

**Comment by SnakeDoc83** [comment]
Closed via https://github.com/inorichi/tachiyomi-extensions/pull/3556
