### ISSUE TITLE
[Source Request] Yakusoku no neverland

### ISSUE THREAD

**Issue by Fooftilly** [inorichi/tachiyomi-extensions#1941]
### Source Website
Website can be found at <https://yakusokunoneverland.com/>.

**Comment by SnakeDoc83** [comment]
Normally I don't ask, but why?  They have just 3 manga and they're ones you could probably find in a dozen sources we already have.

**Comment by 0klux** [comment]
Dunno, we already have some sources focused on like, only one series, which can be found on various sources already. Guya and Kaguyadex are big examples. So I don't see why not.

**Comment by SnakeDoc83** [comment]
The Guya extension was made by the person who made the website (or is associated with them, can't remember exactly).  He wanted it so he made it.  Kaguyadex took 2 lines of code to implement because it's part of a multi-source extension.

Maybe there's something worthwhile with this website, I don't know.  You never know with most source requests but I give most the benefit of the doubt.  I don't see it here though; so I'm asking.

**Comment by Hyoretsu** [comment]
@SnakeDoc83 This manga though, Manga Plus already officially releases it in English and it's actually the first one amongst even scanlation sites

**Comment by as280093** [comment]
**Here are the icons:**
[ic_launcher .zip](https://github.com/inorichi/tachiyomi-extensions/files/4050303/ic_launcher.23.zip)

**Comment by CarlosEsco** [comment]
No plans to implement this as plenty of other sources have these manga and it's not a scanlator just a very small aggregator
