### ISSUE TITLE
[Bug] TuMangaOnline : unexpected url: var url =

### ISSUE THREAD

**Issue by AbreuHD** [inorichi/tachiyomi-extensions#1957]
### Device information
* Tachiyomi extension version: 1.2.13
* Tachiyomi version: 0.8.4
* Android version: Android One (9)

## Steps to reproduce
1. First Step... get into any manga
2. Second Step... try to see any chapter

### Expected behavior
This should have happened

See the chapter

### Actual behavior
This happens instead

unexpected url: var url =

**Comment by happywillow0** [comment]
tumangaonline no funciona actualmente, es debido a los cambios que hacen para rastrear bot's. 
actualmente sigue funcionando lector manga, que es de los dueños de tmo.

TuMangaOnline does not work currently due to the changes they make to track bot's.
Lector Manga (also by the same people) is currently still working. 
NineManga ES is also an option.

**Comment by faritvidal** [comment]
I have a oneplus 6t, I use the version of extension 1.2.13 and 1.2.14 but there is a problem showing me this comment "Expected URL scheme 'http' or 'https' no colon was found" you can check it
