### ISSUE TITLE
[Bug] Remove Manga Rock extension

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#2014]
Manga Rock has posted on their official website that we can no longer read anything there.

![Capture](https://user-images.githubusercontent.com/34897862/71959194-1e4bfe00-31c0-11ea-9bf8-f92fd30250ef.PNG)

Source: https://mangarock.com/

The extension, which used to scrape the website, is thus no longer functional and won't ever be again. It should be removed immediately to avoid future installation.

**Comment by Unit88** [comment]
I'm pretty sure the reason it's not removed immediately is to give people ample time to deal with moving from the MangaRock source. If the extension was just immediately removed, I'm sure a fair amount of people would be pretty pissed at all the info that would disappear with it. What manga they were reading there that needs to be migrated, what chapters you read, bookmarks, etc.

A little confusion to the few people who somehow know Mangarock and want to use the extension but aren't aware it's dead is probably worth it over actually angering a bunch of people by erasing everything already

**Comment by happywillow0** [comment]
Actually removing the extension will only take it out of the available extensions to install.
It will not affect anyone who has it already installed as the extension will remain on the phone locally. There is NO function to remotely wipe a phone. 

Due to the popularity of MangaRock however, a "update" that puts a clear message that they shut down may be better before fully removing the extension from the list.

**Comment by joseph619** [comment]
Removing extension has zero effect on Library and Downloads, I have no idea where you got your information from @Unit88
