### ISSUE TITLE
[Bug] UniversoYuri : chapters are not seen "Black Screen and show retry" (MyMangaReadeCMS)

### ISSUE THREAD

**Issue by AbreuHD** [inorichi/tachiyomi-extensions#2033]
### Device information
* Tachiyomi extension version: My Manga Reader CMS v1.2.26
* Tachiyomi version: Latest
* Android version: 9

## Steps to reproduce
1. First Step... Open a manga
2. Second Step... click to see a chapter

### Expected behavior
This should have happened
see the chapter

### Actual behavior
This happens instead
retry button

### Other details
she does not love me

**Comment by happywillow0** [comment]
I can't tell if the website is having trouble or if it is my connection. Their images are taking a while to load and some even time out on Chrome.

**Comment by Rosnbck** [comment]
Same issue with multiple mangas on Mangalife. A few examples: one-punch man, Tower of God. These are just example, there are many more.

**Comment by happywillow0** [comment]
@Rosnbck 
Every source works differently since they are different websites. You should double check if there is an issue for the source / website you are looking at. Mangalife had different issues than UniversoYuri. That said, we just fixed Mangalife again. 

@AbreuHD 
Want to check again, the website is loading faster for me and a couple of mangas I tested are loading fine.

**Comment by SnakeDoc83** [comment]
@arkon Source is working but it's slow; more than likely it was dead-slow at the time.  Also, `.connectTimeout()` was added to the `client` a few days ago, nothing else to do here.
