### ISSUE TITLE
[Bug] Mangadex : HTTP error 403 on Mangadex extension

### ISSUE THREAD

**Issue by tht1Asian** [inorichi/tachiyomi-extensions#2036]
### Device information
* Tachiyomi extension version: 1.2.76
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Open Mangadex and Read Manga fine
2. Open different Manga and HTTP 403 error occurs
3. Close and Reopen Mangadex extension and no Manga appear and HTTP 403 pops up

### Expected behavior
Open Reader Normally

### Actual behavior
HTTP 403 Error

### Other details
The reader will work, then stop working and gives the HTTP 403 error, then start working again after an hour. It keeps occurring. Works perfectly fine on web browsers.

**Comment by arkon** [comment]
#2031

Wondering if we need rate limiting?

**Comment by CarlosEsco** [comment]
@arkon there is last i knew

**Comment by ZeroExistence** [comment]
Isn't this because of MangaDex's CDN? I encountered this issue, and just open the manga via WebView. It prompt me into CDN's traffic page. Just answer the captcha in that CDN's page, and it will fix the issue temporarily. I assume Tachiyomi still use the CDN's cookie to access MangaDex, so it should work for a day or something.

It's possibly an issue with the MangaDex's new CDN, if you make a lot of traffic to the site.
