### ISSUE TITLE
Mangadex: Older chapters unavailable due pagination 

### ISSUE THREAD

**Issue by Intervencion** [inorichi/tachiyomi-extensions#207]
Versions: Any

Since recent changes on mangadex older chapters are unavailable for tachiyomi since they get cut out. 
Check https://mangadex.com/manga/153/. Tachiyomi only shows until 925.

**Comment by CarlosEsco** [comment]
I have a fix currently but it requires this since pagination doesnt work on old urls.
https://github.com/inorichi/tachiyomi/pull/1262

Though im messaging holo since pagination is gonna cause more server load then normal, for example 10 page requests for conan.   Gonna see if he can add a /all after the url to show all chapters.

**Comment by Intervencion** [comment]
Wouldn't an API be way better than a /all?

**Comment by CarlosEsco** [comment]
haha leave that circle jerk back in their discord channel 😄

**Comment by Intervencion** [comment]
We tryin' man, we tryin'...

**Comment by CarlosEsco** [comment]
#216
