### ISSUE TITLE
[Bug] LectorManga: unknown method

### ISSUE THREAD

**Issue by contaku91** [inorichi/tachiyomi-extensions#2256]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9
I updated the manga on my device but when I try to open or download it gives me the error on the image.

1. Update manga
2. Try to open the new chapter
3. Error it doesn't load/open

![Screenshot_20200216-142741](https://user-images.githubusercontent.com/61115631/74606613-d3c87600-50c9-11ea-9f42-97f0d0ed5202.jpg)

**Comment by happywillow0** [comment]
Everything looks right for Lector Manga. They haven't changed that part even on TMO.

Check your connection and try to load something from the catalog screen.

Is it happening with a specific manga and chapter?

**Comment by contaku91** [comment]
All manga from Lector manga... Even from the browse page, any chapter that is not already downloaded

**Comment by happywillow0** [comment]
I suppose since you are looking at the library updates, app is trying to do many things at once.

There is a rate limit in the extension but you still can trigger error 429 too many requests.

That page might have caused the error because that part does not check for error messages and assumes the page is what you want.

Give it a few minutes to let the very short temp ban go away.

**Comment by happywillow0** [comment]
Or, open up the webview or browser. There are some new checks were they started banning ip.

You might want to migrate to another source.

**Comment by happywillow0** [comment]
I think we can close this for now. The error message is different so this doesn't really apply anymore.
