### ISSUE TITLE
[Bug] LectorManga : Some pages are not downloaded

### ISSUE THREAD

**Issue by rs3mk** [inorichi/tachiyomi-extensions#2278]
### Device information
* Tachiyomi extension version: last
* Tachiyomi version: last
* Android version: ?

## Steps to reproduce
1. Download Social anxiety vs Yuri (all chapther)
2. Some pages are not downloaded, they are skipped.

### Expected behavior
Capítulo 18.00 -> 2 pag.

### Actual behavior
Capítulo 18.00 -> 1 pag.

**Comment by happywillow0** [comment]
I'll have to look into why it's still dropped pages.
Meanwhile, you should be able to switch the extension preference to paginated rather than Cascade to use bypass this issue

**Comment by happywillow0** [comment]
Can you confirm the extension version?

**Comment by happywillow0** [comment]
I'm blaming this on the people who run the site. 

A while back, to annoy users who are using apps or other websites that were stealing images, they started inserting fake images into the cascade view. The website itself has code to hide the fake images. 

I'm finding that in this case, the 4koma manga has so few pages that the fake image code seems to be breaking. It would generate 1 fake page but mark 2 of them to hide. 

You can test this out by opening up say chapter 42 in cascade view in a (desktop) browser and keep hitting refresh. Sometimes, one of the pages gets hidden when it is not supposed to. 

Again, the paginated is not affected so I recommend switching to that when this issue comes up.

**Comment by rs3mk** [comment]
Works in cascade mode.

thx
