### ISSUE TITLE
[Bug] Mangalib (RU) : Some pages refuse to load

### ISSUE THREAD

**Issue by oplexz** [inorichi/tachiyomi-extensions#2351]
### Device information
* Present in all recent extension versions, including latest (1.2.13)
* Seen on Tachiyomi version 0.8.4, 0.8.5 and J2K 0.9.81
* Android versions: 5.0.2, 9, 10

## Steps to reproduce
1. Read manga
2. Stumble across a page that doesn't load
I don't think there's actually a way to reproduce it on purpose, because it occurs every now and then randomly. (see Other details)

### Expected behavior
The image should have loaded

### Actual behavior
There is nothing but a "retry" button on the page

### Other details
I know this bug report gives literally no information about why this is happening, but I've been trying to realize why this could be happening for a while now, and so far I only found a temporary fix (until it occurs again, out of nowhere): clearing extension's cache via Android settings.
That does the job, and everything loads properly, but that is a _temporary_ fix. If I can somehow help to trace down the reason, I'll be happy to do so.

**Comment by happywillow0** [comment]
I looked at the code and have a rough idea of how things are supposed to work. 

However, are you saying that it is not consistent / repeatable?
It is not something you have a example of for a specific manga, chapter, page number?

Also, since it is happening for the pages, have you tried just going to Tachiyomi, Settings, Advanced Settings, Clear Chapter Cache?

**Comment by oplexz** [comment]
@happywillow0 it is **not** consistent and I have no idea how to reproduce this issue.
There are no specific mangas that cause this error to appear, but I remember one that definitely erorred: "Koi Shita no de, Haishin Shite Mita"
I'll try doing what you said the next time it appears.

**Comment by BlueCat300** [comment]
@happywillow0 
This site has 2 image servers img2 and img3.
img2 for full scans and img3 for compressed scans. When an application tries to download images, a site can return them with the htm or webp extension, it can create errors with the retry button.
There is no problem when the extension makes a url list of images. Perhaps the site is protected from applications such as tachiyomi.
It is necessary to test with the extension on version 1.2.12 and the "основной" server because the latest update removed the server choice.
Manga for testing - Gochuumon wa Usagi Desu ka? chapter 4.

**Comment by oplexz** [comment]
@happywillow0 well, that took a long time, but it has finally occured again. What should I do to give you the most details on what's wrong?

**Comment by SnakeDoc83** [comment]
@oplexz Seems their website is 404ing right now, nothing to do.

**Comment by oplexz** [comment]
@SnakeDoc83 Oh, pardon then.

Guess this issue will be open for a long time, because nor me, nor my friends can reproduce this again.

**Comment by SnakeDoc83** [comment]
Closing because of changes to source's site and extension.
