### ISSUE TITLE
[Feature Request] Mangadex: Latest Tab No Longer Has Infinite Scroll

### ISSUE THREAD

**Issue by citricsquid22** [inorichi/tachiyomi-extensions#2355]
The "Latest" tab for Mangadex only loads a fix amount of titles. Before I updated to the latest extension update and 0.8.5, it had infinite scrolling/loaded infinite titles.

Will changing the source to https://mangadex.org/titles/1 resolve the issue?

**Comment by happywillow0** [comment]
Yes and no.

It does look like the updates pagehttps://mangadex.org/updates doesn't go on for too long (example it is showing 58 titles for me )

There is a "bug" on Mangadex end where the titles page doesn't respect language. So the order may likely be out of order because of other language updates.

You can preview what it will be like I think in Browse and a sort filter for updates.

**Comment by happywillow0** [comment]
Also, are you properly logged in via webview? 

Logged Out, updates show 54 titles
Logged In, it latest updates shows me there are 824 (English) titles

**Comment by citricsquid22** [comment]
Yes, logged in through Web View I still get a fixed number of titles in the Latest tab (going through the Catalogue menu, ~58) Yesterday it briefly had infinite scroll, but after leaving the Latest tab it was broken again. It seems to be broken ~95% of the time.

**Comment by arkon** [comment]
This seems to be an issue with the site. I've occasionally seen it only give me 1/2 pages too (on the site itself), but I couldn't figure out why.
