### ISSUE TITLE
Mangadex: Unparseable date

### ISSUE THREAD

**Issue by yambadr** [inorichi/tachiyomi-extensions#238]
Tachiyomi 0.6.8
Mangadex 1.2.12

I get this error when trying to update any manga

> Unparseable date: ""

**Comment by CarlosEsco** [comment]
Can you be more specific what manga are causing this issue. I am not seeing any issue on my end

**Comment by yambadr** [comment]
All the mangas I added to my library from mangadex. That includes: Detective Conan, Tomo-chan wa onna no ko, Baby steps, Silver spoon, Fullmetal alchemist, etc.

**Comment by CarlosEsco** [comment]
What screen gives you the unparseable date

**Comment by CarlosEsco** [comment]
Can you attach a screenshot

**Comment by Echoffee** [comment]
Can confirm it happened to me about one hour ago. Every manga from Mangadex cannot be read, every chapters are marked as unread without titles, and number of chapters on the "Info" screen from a manga is displaying "-1".

[Linking up](https://imgur.com/a/WFP3O) a screenshot of what's happening when trying to read any chapter.

**Comment by yambadr** [comment]
I cleared the cache and restarted the app. Now I get this error only on detective conan and Tomo pages.
![screenshot_20180307-232025](https://user-images.githubusercontent.com/17810950/37118976-a7c4fcfe-225e-11e8-8c4c-13090ce5c79c.png)

**Comment by CarlosEsco** [comment]
Weird I get none of this on my library manga or uncached browse.  I will try to verify the Json result later

**Comment by CarlosEsco** [comment]
I see the issue let me get something out.  Can you both test 1.2.13 once its released

**Comment by CarlosEsco** [comment]
#239

@yambadr and @Echoffee  you guys will also have another problem which i cant fix from my end.  

Basically mangadex started with urls using only the ids so /manga/1
at somepoint last month they switched to adding the manga name in the url too.
/manga/1/tower-of-god

Both urls are still valid.  However there was a short time period where the extension wasnt adjusted to trim off the manga name.  This caused an issue where some manga in library are just /manga/id and some are /manga/id/name.

On the outside that doesnt seem like an issue but what happened is if i had tower of god (/manga/1) in my library and i search it again in mangadex.  It shows not added because the unique identifier is the url.  
So you could technically have tower of god from mangadex in your library twice..

After this issue came up i pushed a release like 1.2.5 or something that trims off the manga name so they are seen as matches.  

Your guys is problem (I had this issue too for 2 manga in my library)  is we added the manga during the name switch so the library version is /manga/id/name.  So 
1.  you are gonna see the manga as not added if you search it again.
2.  It was causing the api error cause it assumed the only the number was after the 2nd to last.

Number 2 i fixed.  However the only way to fix number 1 is search mangadex for that manga add it.  then remove your old one from library.

**Comment by CarlosEsco** [comment]
@Echoffee if 1.2.13 doesnt fix your issue please cache and restart like yambadr did

**Comment by Echoffee** [comment]
Thank you very much, looks like it's working again, also the thumbnails are back and are displaying much faster.

For some reason, I had the Mangadex Tachiyomi extension installed twice, so it might also have broken something on my end (maybe a remnant of the F-droid app), and the source migration feature is working for the MangaDex -> MangaDex re-adding.

But yeah, it's now fixed, thanks again.

**Comment by yambadr** [comment]
Thank you. It's all good now.
