### ISSUE TITLE
[Add Extension] Readm.org

### ISSUE THREAD

**Issue by banra123** [inorichi/tachiyomi-extensions#2441]
### Source Website
Website can be found at https://readm.org/

**Comment by ZEXERJK** [comment]
+1

**Comment by ZEXERJK** [comment]
Add it please, it's a source where everyone other aggregator sites are picking the manga/manhua/manhwa recently because they are the first to upload every time.
@einstein95 @happywillow0 @arkon (sorry for the tag but it's very important and it seems you three are the only one reading our posts...thanks :) )

**Comment by CarlosEsco** [comment]
Don't tag people randomly.

**Comment by ZEXERJK** [comment]
> Don't tag people randomly.

I tagged those people to bring attention to this important source because nobody was responding or saying anything, It was the first time that I tagged people in this thread and apparently the last one if these are the consequences. I also find this pretty harsh for only a tag, I did it with the most good intentions and not for 'bothering people' or anything of the sort. Anyway thanks guys for your work. Awesome App!

**Comment by CarlosEsco** [comment]
These are requests for sources by users and there are no guarantees the source will be added. If anything pinging people to "bring attention" will just push the few developers who do sources away from doing it.

**Comment by ZEXERJK** [comment]
> These are requests for sources by users and there are no guarantees the source will be added. If anything pinging people to "bring attention" will just push the few developers who do sources away from doing it.

Now that I know, I won't do it ever again, you can also see searching my "issue tickets" that I tried to contribute to this app in my little to pinpoint bugs and giving detailed information to try to solve them, I also proposed sources that are quite known just because I really like this app and I'm grateful to the work that all the developers are putting into it. Anyway thanks for the answer and to let me clarify what I was trying to say.

**Comment by happywillow0** [comment]
I'm still busy with work (healthcare = essential worker), and I have a few more important things I really should do such as my taxes. 

That said, I took a quick look and ReadM actually is pretty easy to scrape / parse from so the basic should be pretty easy to put together. Most of it is just a straight pull from the website with the exception of search which needs a post and json parsing.

**Comment by ZEXERJK** [comment]
> I'm still busy with work (healthcare = essential worker), and I have a few more important things I really should do such as my taxes.
> 
> That said, I took a quick look and ReadM actually is pretty easy to scrape / parse from so the basic should be pretty easy to put together. Most of it is just a straight pull from the website with the exception of search which needs a post and json parsing.

Thank you for your work in the healthcare field particularly in this moment of need against the virus, I really appreciate that you took your time to check this source with all the things that you have to do that are certainly more important. Thank you very much.

P.S. I hope that you and your relatives and close friends are all safe and in good health.

**Comment by banra123** [comment]
There also a site readmanga today, there you can read 90% similar like in readm
