### ISSUE TITLE
[Source Request] YACReader Library

### ISSUE THREAD

**Issue by bmix** [inorichi/tachiyomi-extensions#2451]
### Source Website
No public URL. This stuff gets hosted locally.

### Other Details
There is an [open source Comics Library & Reader, called YACReader](http://www.yacreader.com). It can serve the user's library via HTTP. The HTML interface is simple, it orders the catalog via following alphanumeric logic, where each digit/character collects comics, whose title starts with the same character:

	Library Name (can have several libraries)
	|_0
	|_1
	|_2
	|_etc.
	|_A
	  |_Agents of Shield
	  |_Akira
	  |_All You Need Is Kill
	  |_etc.
	|_B
	|_C
	|_etc.

Access is done via simple URL paths:
`http://192.168.1.199:8090/library/1/folder/2`
`http://192.168.1.199:8090/library/1/folder/335`

I have not yet investigated much, but it seems, that the libraries are simply numbered, and all the folders are also simply numbered (the last URL points to `Libraries  > Standard > The Umbrella Academy` on my system.

I am aware, that Tachiyomi's purpose is a little bit different, but, as

* there is no YACReader client for Android, only iOS
* all Android comic reader apps I know are old and out of development
* it's nice to have a single entry point to a topic, rather than a thousand applications
* access is via simple web requests

I would be very happy, to be able to access my YACReader Library with Tachiyomi. Thank you.

**Comment by CarlosEsco** [comment]
are the comics stored as images or zip/rars?  Since that will be the biggest sticking point

**Comment by bmix** [comment]
Ah! Yes, I see your point. I didn't think about this...

They are added as archives. I just tested, whether the software recognizes a folder of pictures, but it doesn't. You're right, this is completely different in concept, than scanlation sites, where the comics are served as pictures.

**Comment by CarlosEsco** [comment]
yea there isn't a current way to rar/zip

**Comment by 2ion** [comment]
@CarlosEsco Excuse my ignorance, but doesn't Android itself include zip file support, which would allow cbz support as a first step? Nevermind RAR. I haven't written for Android before but I wouldn't mind giving this a shot if there's not a total dealbreaker in here, as I'm currently looking at writing either a separate app or a better web gallery for Yacreader for personal use. Or are Tachiyomi extensions somehow limited in which parts of the Android API they are allowed to access or how much state they are allowed to keep? Since ZIP allows random access it shouldn't be too difficult to handle this with some code. Of course, a bulk download of each cbz will be necessary as the central directory part of the zip files is at the end of each zipball which will slow down working with this kind of source quite a bit.

**Comment by CarlosEsco** [comment]
> @CarlosEsco Excuse my ignorance, but doesn't Android itself include zip file support, which would allow cbz support as a first step? Nevermind RAR. I haven't written for Android before but I wouldn't mind giving this a shot if there's not a total dealbreaker in here, as I'm currently looking at writing either a separate app or a better web gallery for Yacreader for personal use. Or are Tachiyomi extensions somehow limited in which parts of the Android API they are allowed to access or how much state they are allowed to keep? Since ZIP allows random access it shouldn't be too difficult to handle this with some code. Of course, a bulk download of each cbz will be necessary as the central directory part of the zip files is at the end of each zipball which will slow down working with this kind of source quite a bit.

The main app would require extensive rewrites to support zip/cbz from an http source.  This would also require not break any existing extension when changes are made.  The app already support reading in these formats when they are local manga.
