### ISSUE TITLE
Team x doesn't work

### ISSUE THREAD

**Issue by seiif1** [inorichi/tachiyomi-extensions#2467]
### Device information
* Tachiyomi extension version: 1.2.3
* Tachiyomi version: 8.5
* Android version: 9

### Other details
When i try to refresh a manga i get a java error
![Screenshot_20200321-170614_Tachiyomi](https://user-images.githubusercontent.com/62269578/77230704-4e3b5880-6b96-11ea-9f5b-79a93de80410.png)

**Comment by mged** [comment]
teamx not working
i cant even laucnh it when i click browse it show me failed to bypass cloudfire 

please fix this issue fast my fav manga is only on teamx and i cant accsess that website on a pc/laptop right now :C fix it fix it fix it

**Comment by happywillow0** [comment]
The Team X site is having server issues right now. Due to likely heavy load, the server is taking longer to connect to. 

Currently, the app waits up to twelve seconds for cloudflare and around 10 seconds for the site. 
 
It is taking around  10 seconds to load pages. That means:

1) Cloudflare check + the site is taking too long will result in failed to bypass cloudflare. You can bypass this temporary by opening up the site in webview and allowing the cloudflare to pass and the site to load.

2) Passed cloudflare -> site only, the extension may load or you may get timeout errors. 502 errors also happen when the server messes up communication as well. 

We will have to wait until the server gets better.

**Comment by mged** [comment]
So devs dont have to make any changes? so we will just wait and see if its going to be fixed or not?

ok

**Comment by arkon** [comment]
Why would the app developers be responsible for the site not working on your laptop either?

**Comment by mged** [comment]
i think you misunderstood something...

or i did idk. but the website work on the laptop but i cant use the laptop to read manga (or anything elese) im making at as a server thingie and its busy 24/7 :C
so please if its an issue fix it and if its a case of time lets wait :)

**Comment by mged** [comment]
its useless, as i expceted the issue is not related to the server load ( what kind of reasons is this anyway lol ) 

the error says cloudfire bypass issue so its not a server load related issue, plus its been from a period of time but i was think you fixed it, when i came to watch my fav manga on that extension i found that its not working as it used to be. i really dont know why they release new versions for it, they release broken useless versions just to ... idk just for what i dont know its funny somehow lol

i think i will wait until my laptop fiinsh the server thingie and read manga on it coz my favorite and beloved manga reader app is not working :cry:

**Comment by mged** [comment]
Failed to bypass cloudflare please fix this issue :pray:

**Comment by mged** [comment]
still not working

**Comment by arkon** [comment]
See response in https://github.com/inorichi/tachiyomi/issues/2750
