### ISSUE TITLE
[Bug] Pufei: Downloaded comics cannot be opened

### ISSUE THREAD

**Issue by aylz10** [inorichi/tachiyomi-extensions#2480]
### Device information
* Tachiyomi extension version: 1.2.3
* Tachiyomi version: r1936
* Android version: 10

## Steps to reproduce
1. First Step
Download comics
2. Second Step
Open comics

### Expected behavior
This should have happened
display image

### Actual behavior
This happens instead
toast is displayed as "Page list is empty"

### Other details
After checking, I found that the downloaded comic picture suffix is ​​".bin"

**Comment by einstein95** [comment]
This seems to be an issue with Tachiyomi itself as it is trusting what the server is saying what the page files are when saving.

Technical answer: Because the server, when `http://res.img.220012.net/images/2019/11/22/10/08a97c23d2.jpg/0` is requested for example, responds with `Content-Type: application/octet-stream`, Tachi saves it as `.bin` instead of `.jpg` which is what the file actually is.

**Comment by arkon** [comment]
Not entirely sure why Android decides to give it a `.bin` extension (it just keeps it extension-less on macOS), but yes that'd be the reason why.

I'm not sure if there's a good catch-all way for the app to handle that. The extension could specifically try to handle edge cases like that via an interceptor.

**Comment by happywillow0** [comment]
I took a quick look at changing the content type with an interceptor but either I messed up or it doesn't work like I expected to. Does the downloader use content type to save the extension or it is normally the url and the given file extension?
