### ISSUE TITLE
[Bug] Manga Plus: Not loading on dev

### ISSUE THREAD

**Issue by ChrRubin** [inorichi/tachiyomi-extensions#2512]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: dev r1940
* Android version: 6.0.1

## Steps to reproduce
Go to Catalogues and press Browse/Latest on Manga Plus.

OR

Update chapter list on a manga from Manga Plus.

OR

Read a chapter from Manga Plus.

### Expected behavior
Manga and chapters should load fine.

### Actual behavior
Everything related to Manga Plus loads indefinitely with no error messages.

### Other details
The extension works fine on stable v0.8.5, this issue is only present on dev.

**Comment by alessandrojean** [comment]
I tried now with the same dev version and it loaded normally. Have you tried to clear the cache and the database at settings?

**Comment by ChrRubin** [comment]
Yeah I've tried those and it's still not loading. I don't remember what dev version I was using before but the extension was loading fine before I updated to r1940 recently.

**Comment by alessandrojean** [comment]
I will try to reproduce the problem later in an emulator with the same android version as yours and try to fix if it happens.

**Comment by MercerBoi** [comment]
Exactly the same issue here, with the exact same device information too!

**Comment by alessandrojean** [comment]
I tested on the emulator, with the same android version, and [it loaded normally](https://imgur.com/oMMsnRa) too, not able to reproduce the problem :(

I have a supposition of what can be the cause of the problem. Can you install [this modified version](https://file.io/5TLqQx) of the extension that uses Duktape for deserializing (probably will need to uninstall the extension first and then install the apk) and check if the issue happens too?

**Comment by ChrRubin** [comment]
That link returned a 404. As a side note, I tried uninstalling and reinstalling the same version of the extension just to see if that'll work, but it's still not loading.

**Comment by alessandrojean** [comment]
I've tested now using Duktape but some issues happened, I'm trying to fix and will reupload another apk soon.

**Comment by ChrRubin** [comment]
Yup the above modified apk throws `ReferenceError: identifier 'require' undefined` when trying to load anything related to Manga Plus.

![error](https://cdn.discordapp.com/attachments/516491285251620874/692773214069456896/IMG_20200327_003259.png)

**Comment by alessandrojean** [comment]
Just linking because it's related: #1697.

**Comment by alessandrojean** [comment]
I don't know what is causing this error in Duktape related to the `require` function, but since it's giving an error and not getting stuck loading, I can already assume the infinite loading is related to the `kotlinx.serialization` in devices with Android 6.

I'm just assuming again, but it can be related to the main app using Kotlin 1.3.70 and the extension repo using 1.3.60, maybe some incompatibility is happening. The `kotlinx-serialization-runtime` is outdated too (the current one is version 0.20.0) because of the Kotlin version used in this repo, and can't be updated unless the Kotlin is updated too.

@arkon, any thoughts?

**Comment by alessandrojean** [comment]
Confirmed now that the `require` error in Duktape is caused only on dev version, probably some incompatibility with the Kotlin version used (1.3.70), because in stable v0.8.5 (Kotlin 1.3.60) it works fine. 

@ChrRubin, @MercerBoi can you test [this other apk](https://send.firefox.com/download/83b482e08c32da75/#5o1v3wZ5GvQJOwF0huaDIw) and see if it works?

**Comment by ChrRubin** [comment]
Yup the new apk you provided works on both dev and stable.

**Comment by alessandrojean** [comment]
So, the thing is, this apk was compiled using Kotlin 1.3.70 and the latest version of kotlinx.serialization lib (runtime + protobuf 0.20.0). I have locally updated the Kotlin version of the repository, and the apk generated *worked fine too with both dev and stable* (even if it uses a lower Kotlin version), tested in both Android 6 and 10. 

However, I don't know if it's okay to submit a PR at the moment to update the Kotlin version of this repo along with the modifications to the MangaPlus extension, because it could have a risk of breaking something to stable users. @arkon, is it okay if I submit a PR bumping the Kotlin version of the repo to fix this issue now or it's better to wait for a new stable release?

**Comment by arkon** [comment]
Can you test against stable in Android 4.x (I forget what the lowest supported version is) and 5 too?

It should at least work for 5. If it doesn't work with 4.x, I'm fine with that since they can stay on the older extension.

**Comment by alessandrojean** [comment]
Sure, I can test with Android 4.4.4 and 5.

**Comment by alessandrojean** [comment]
Tested now and working fine with Android 4.1 in [stable](https://imgur.com/vLox4ZS) and with Android 5.0 in [dev](https://imgur.com/xGu7xzF) and [stable](https://imgur.com/t5Tc8t9). I will submit a PR then :)
