### ISSUE TITLE
[Bug] wpmangastream : Kiryuu image retry bug

### ISSUE THREAD

**Issue by Riztard** [inorichi/tachiyomi-extensions#2624]
### Device information
* Tachiyomi extension version: 1.2.6
* Tachiyomi version: j2k 0.9.82
* Android version: 9

## Steps to reproduce
1. Find manga The Hunter
2. open
3. choose chapter 49
4. 2nd image and 3rd error (it wasn't supposed to be an image) *sometime only one image

### Expected behavior
This should not have exist

### Actual behavior
Showing error (retry)

### Other details
Dominate the Three Realms for other example

**Comment by E3FxGaming** [comment]
> 2nd image and 3rd error (it wasn't supposed to be an image) *sometime only one image

The website says there should be images though? It uses the HTML img element to say that there should be two images.

![image](https://user-images.githubusercontent.com/8276268/78867656-b5d01f80-7a41-11ea-8506-1fa5c70e2717.png)

The links which they provide with the src attribute for the img elements can't be resolved to proper images, but that's an issues already present on the website and not something our extension is causing.

If you want this fixed, you should probably tell the the website owner instead of us.

**Comment by Riztard** [comment]
i dont think the image was important for the manga chapter, and i think its been so long time already. maybe way to annoy 3rd party software?
cant it get excluded?
