### ISSUE TITLE
KissManga Site Admin's Statement regarding IP Bans

### ISSUE THREAD

**Issue by AccelerateIzaya** [inorichi/tachiyomi-extensions#2719]
Hello Hello, to whom it may concern.

The Site Admin of KissaManga says:

> We will unban the IPs after tachiyomi remove the kissmanga extensions, dont know how long will it take.

Here is the source: [Click Here](https://www.reddit.com/r/KissCommunitySupport/comments/g2h8z4/no_adblock_on_kissmanga/fnlf2iz/)

Sorry if this issue doesn't belong here. But I had to relay this information somehow. Please reconsider keeping the KissManga extension in the app.

Thank you

P.S. I am not the person in Reddit who started this conversation.

**Comment by joseph619** [comment]
You don't even use Tachiyomi so I don't see why we should remove an extension for a non-user. You are free to use other manga sites, Kissmanga is not the only aggregator.

**Comment by AccelerateIzaya** [comment]
I do use Tachiyomi. Mainly mangakakalot. But I am here simply to relay this information. 
Also, how did you get the impression that I do not use Tachiyomi?

**Comment by joseph619** [comment]
I thought you were the person on the reddit post. Nvm.

**Comment by AccelerateIzaya** [comment]
No, haha. The user is someone else.

**Comment by arkon** [comment]
We've never considered taking it down, nor have they ever directly reached out to us about it.

**Comment by AccelerateIzaya** [comment]
Hi, I forwarded your message to the KissManga site admins, and here's what they said:

> With the same reason that tachiyomi devs will not contact me, we will not contact tachiyomi developers. [(Source)](https://www.reddit.com/r/KissCommunitySupport/comments/g57wf7/regarding_tachiyomi_ip_bans/)

I'm not sure if either of you will contact each other in the future. But here's the message they shared. If possible, please consider contacting them. It'll be a huge help in solving the massive IP ban currently happening. :(
@arkon

**Comment by arkon** [comment]
It won't solve the IP ban. They're indiscriminately banning people based on traffic from Tachiyomi (however they determine that).

It's the same as them banning people using regular ad blockers too.

If they really do want it to be taken down, they'll need to directly reach out to us rather than commenting on Reddit to users.

**Comment by arkon** [comment]
It won't solve the IP ban. They're indiscriminately banning people based on traffic from Tachiyomi (however they determine that).

It's the same as them banning people using regular ad blockers too.

If they really do want it to be taken down, they'll need to directly reach out to us rather than commenting on Reddit to users.

**Comment by arkon** [comment]
Keep in mind that they're only doing it because it's affecting their ad revenue.
