### ISSUE TITLE
raw.senmanga.com

### ISSUE THREAD

**Issue by drac0300** [inorichi/tachiyomi-extensions#28]
//Would soneone please add a raws source such as
https://raw.senmanga.com
// as was asked here :
//https://github.com/inorichi/tachiyomi/issues/404

**Comment by j2ghz** [comment]
(CATALOGUE) SOURCE REQUESTS: One source per issue, create more issues if you have more websites Check for duplicates, use search (in issues, not the global one) Put the name of the site as Title, replace this text with clickable link to the site

**Comment by rouji4256** [comment]
Would love to have this implemented! I'm using mangarock as of now (bought it literally yesterday) due to it's ability to change homepage and I really love the function to look at all the just updated manga with a rough time as to when they were uploaded. But I really dislike the touch controls for mangarock when you're actually reading something, and the fact that rocks seem to be coming even to the paid edition. I am already looking for other apps due to the lack of raw manga and the fact that I hate ads and micro transaction. Really hope senmanga is implemented!

**Comment by null-dev** [comment]
I would love to do this, but I'm not sure what currently going on with
https://beta.senmanga.com/.

What is "beta.senmanga.com" exactly, is it a new version of the website?
Because if there is a new version of the site coming out, I want to wait
until that is finalized, then I can work on a source for it.

**Comment by rouji4256** [comment]
@null-dev I am not sure what that is about but it has been in beta for very long now. I think that it is worth making an extension even if it is in beta right now as it will probably still stay in beta for quite a long time.

**Comment by rouji4256** [comment]
@null-dev Hi, I just got a reply from Sen Manga team on FB after asking them on the messenger. Apparently, beta.senmanga.com is a place for them to test any new updates sort of like Blizzard's PTR. According to the admin, most of the beta's updates are already in raw (main site) so it is essentially a clone right now. 

Below is a screen capture of the conversation.
![what is beta senmanga](https://cloud.githubusercontent.com/assets/26888326/25444387/810254e6-2add-11e7-8f0c-4f4eb3dbf979.jpg)

**Comment by null-dev** [comment]
Awesome thanks! I'll start working on a source soon then!

**Comment by rouji4256** [comment]
Thanks a lot man! :D

**Comment by drac0300** [comment]
Yes, thanks a lot !
