### ISSUE TITLE
Mangakakalot refresh error 

### ISSUE THREAD

**Issue by chrisvrk** [inorichi/tachiyomi-extensions#2852]
Device information Honor 8 
Tachiyomi extension version: 
Tachiyomi version:  0.8.5
Android version: 8.0.0
Source information
Source name: Mangakakalot
Source extension version: 1.2.8
Checked a manga tryied to refresh it 
Expected behavior
should show me the new 2 chapters 
Actual behavior
![image](https://user-images.githubusercontent.com/47571278/80313867-61c18b00-87f6-11ea-93d6-1a38f69ed47b.png)
This happens instead

**Comment by SnakeDoc83** [comment]
Works fine for me for this manga.  I think this is a case of mangakakalot creating a new entry and the old one dying.

**Comment by chrisvrk** [comment]
sorry i am kind of new to this, like can you define new entry ?? thanks

**Comment by SnakeDoc83** [comment]
As an example: when you bookmarked that particular manga the URL for it was something like mangakakalot.com/the-teacher-can-not-tell-me-love and then sometime later they changed the URL to mangakakalot.com/read-manga1234.  Tachi tries to access the first one (because that's the URL it associates with that manga) but that URL doesn't actually have the manga information there anymore.

**Comment by chrisvrk** [comment]
so i guess only way to fix it is migrate or rerigister ?
thanks for the info btw

**Comment by arkon** [comment]
Yup, you can "migrate" to the new entry.
