### ISSUE TITLE
[Bug] Sources that fail

### ISSUE THREAD

**Issue by Agtui** [inorichi/tachiyomi-extensions#2924]
I want to know if you could repair all bugs of the next sources:

nhentai, tumangaonline, lectormanga, newtoki, bato.to , manga mx

**Comment by SnakeDoc83** [comment]
Nhentai https://github.com/inorichi/tachiyomi-extensions/issues/2920
TMO and Lector https://github.com/inorichi/tachiyomi-extensions/issues/2714
NewToki you need to override the baseUrl
Bato.to https://github.com/inorichi/tachiyomi-extensions/issues/2919
Manga mx - no idea what you're talking about because there are no details at all with your post.

**Comment by Agtui** [comment]
Thanks!!

**Comment by E3FxGaming** [comment]
Regarding Manga mx:
It uses cloudflare, that's why it doesn't work.

Fixed if #2926 is accepted.
