### ISSUE TITLE
[Bug] Ninemanga(en) : App not showing any manga

### ISSUE THREAD

**Issue by thegreatdk** [inorichi/tachiyomi-extensions#3046]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 8.1.0

### Source information
- Name: ninemanga(en)
- Extension version: 1.2.9

## Steps to reproduce
1. Open browse section
2. Click on latest/browse on ninemanga extension

### Expected behavior
List of manga supposed to appear

### Actual behavior
No manga found/just black screen. On web view all seems normal. I can access everything on webview, but not on app

**Comment by MerradOklom** [comment]
Same for me and my friends. Their site is redirecting me to gardenmanage.com when trying to access it from Chrome (mobile). So either the site is broken or they are blocking users in some way.

**Comment by AMZMA** [comment]
how about change NinemangaEN to Taadd.com since basically Niinemanga took image from Taadd (or maybe they both owned by same person)?

Cons of Ninemanga: sometimes you'll get error host warning.
Pros of Taadd: you can scroll further back on latest update list (in mobile view)

Or should I open request for this?
Thank you

**Comment by MerradOklom** [comment]
> how about change NinemangaEN to Taadd.com since basically Niinemanga took image from Taadd (or maybe they both owned by same person)?
> 
> Cons of Ninemanga: sometimes you'll get error host warning.
> Pros of Taadd: you can scroll further back on latest update list (in mobile view)
> 
> Or should I open new request for this?
> Thank you
Yup, I also believe they're owned by the same person, and that person has many other domains (or at least that's what I think because they're backlinking to each other):
https://tenmanga.com
https://nineanime.com
https://niadd.com (there is a Source Request for this one already)
https://addfunny.com
https://novelall.com

You're free to open a Source Request for Taadd but maybe we should wait for a developer's opinion.

**Comment by CarlosEsco** [comment]
if they are same owner and use similar code they could become a factory

**Comment by thegreatdk** [comment]
> if they are same owner and use similar code they could become a factory

Its good then if it can be implemented. I still hopes if we can fix ninemanga first though. But then again its up to the developer. I will be happy either solution.

**Comment by NanayaRyuuichi** [comment]
This also happened to me, It's just blank page.

But webview can open the site normally

**Comment by thegreatdk** [comment]
Thank you!!!
