### ISSUE TITLE
[Source Request] lemonfont

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi-extensions#3061]
### Source Website
- Name: Lemonfontcomics
- Link: http://lemonfontcomics.com/comics/
- Language(s): English (as far as I know)

### Other Details
It's a hentai site

**Comment by ardittristan** [comment]
Here are the icons
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4692238/ic_launcher.zip)

**Comment by ardittristan** [comment]
I tried to code it myself, but am not good enough at kotlin etc to get it to work. But I can give the info I found out.


list of all comics is located at lemonfontcomics.com/comics

comics that are still ongoing have the css tag: `p#tag-ongoing` or `p#tag-ongoing.updated`

and comics that are paid redirect to a link that includes https instead of the http used everywhere else

each comic has the info about series, total chapters and part embedded in it's html code.
![image](https://user-images.githubusercontent.com/42787508/83205613-58a63f80-a14f-11ea-90a6-8b8fac64dbab.png)
I used these regex's to extract the data, could be done with another way that I don't know tho.
`(?<=(window.ptotal ?= ?))[0-9]*(?=;)`
`(?<=(window.series ?= ?')).*(?=';)`
`(?<=(window.part ?= ?')).*(?=';)`

images are saved under
lemonfontcomics.com/assets/comics/`window.series`/`window.part`/`<chapternumber>.padStart(3,'0')`.png
*(I added padStart because numbers smaller than 100 start with 0's)*

each page would probably have to be it's own chapter since it's comics update page per page.
