### ISSUE TITLE
MangaRock Filter with Rank not working.

### ISSUE THREAD

**Issue by Haise-Kakashi** [inorichi/tachiyomi-extensions#320]
MangaRock Filter with Rank not working and giving :
Value<html>of type java.lang.String cannot be converted to JSONObject ?????
Please fix this MangaRock is the only source for me.

**Comment by CarlosEsco** [comment]
Discord works perfectly fine.  I've labeled this as a bug for the mangarock issue

**Comment by Haise-Kakashi** [comment]
Thanks

**Comment by arkon** [comment]
I can filter by rank. What are the exact filters you're using?

**Comment by Haise-Kakashi** [comment]
This started when i filtered romance and rank together and then it started happening in all genres.

**Comment by Haise-Kakashi** [comment]
Only order by Rank doesn't work all the genres work fine when ordered by name.

**Comment by arkon** [comment]
It's a bit weird, I did see the error a few times but it's not consistent. I haven't tried seeing what the actual response is, but I suspect it's some sort of error page (since it says `<html>`). I got the error when I was filtering with the 4-koma genre and ordered by rank, but it worked when I tried that again. I also verified that the website is still sending the same body.

Maybe retry it a few times?

**Comment by Haise-Kakashi** [comment]
Now its occuring even without any genres. Retried plenty times.
When I open the catalogue it should show by name why does it show hot updates maybe that's the issue or it is intentional.

**Comment by Haise-Kakashi** [comment]
After couple of retries and restarts it works without any genres not very consistent tho, but when I filter romance it keeps giving the error.

**Comment by snarkieshark** [comment]
Sorry for the thread necro, just had the same problem and fixed it so I wanted to share in case other people need it.

Just go to Extensions and update Manga Rock. It  should work consistently now.
