### ISSUE TITLE
[Bug] MangaRaw Handshake failed

### ISSUE THREAD

**Issue by sword123k456** [inorichi/tachiyomi-extensions#3233]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: MangaRaw
- Extension version: 1.2.1

## Steps to reproduce
1. Browse from this extension

### Expected behavior
List of manga available from the extension appear.

### Actual behavior
Handshake falied, nothing is loaded

### Other details
A few days ago, I could see and read manga from this extension without a problem. I can also open a manga in browser just fine, the probleme is only while using the app.

**Comment by SnakeDoc83** [comment]
Is this still an issue for you? I'm not seeing it happen.

**Comment by sword123k456** [comment]
Yes, it's still happening for me.

**Comment by AbdullahM0hamed** [comment]
I am now😭😭😭. Will look into it later.

**Comment by ckn4** [comment]
Android P isn't support tls1.3, I think the website only supports tls1.3. Android Q may work fine.

**Comment by AbdullahM0hamed** [comment]
@ckn4 you are right, that's why I specifically made them use http instead of https (and even set the protocol version to http_1_1 - which made manga1001 work at the time).

Currently manga1001 is working for me on 8.1.0, and last time only manga1000 was working. It's really hit or miss, and I haven't been able to get it properly working
