### ISSUE TITLE
[Bug] Manganelo: Loader not implemented message after extension update

### ISSUE THREAD

**Issue by NnjaChurch** [inorichi/tachiyomi-extensions#3282]
### Device information
- Tachiyomi version: 0.92
- Android version: 9

### Source information
- Name: Mangabox (Manganelo)
- Extension version: 1.2.22
## Steps to reproduce
1. Tap on any manga sourced from manganelo
2. Message: source not installed, will pop up (not on all mangas from this source however)
3. Tap a chapter in the manga
4. Message: loader not implemented, will pop up (regardless if the message in step 2 occured)

### Expected behavior
The manga chapter should have loaded abd be able to be read

### Actual behavior
The manga chapter does not load

### Other details
This happened after updating the mangabox extension to 1.2.22, the chapters loaded correctly in the previous version

**Comment by SnakeDoc83** [comment]
I'm guessing the manga you can't load are actually from MangaOnl, not Manganelo.

**Comment by NnjaChurch** [comment]
Its possible. just the ones I cant load have manganelo.com below the chapter name

**Comment by SnakeDoc83** [comment]
The different MangaBox sources sometimes link to each other. The name on the chapter isn't necessarily the source you were using. Look on the info tab for the source name.  MangaOnl was removed on the last extension update due to it being down for nearly a month. 99% sure that's your problem. Use source migration and migrate whatever manga show a bunch of numbers instead of a name.
