### ISSUE TITLE
[Bug] Tapas: Downloaded chapters are not showing in Reader

### ISSUE THREAD

**Issue by duckchomper** [inorichi/tachiyomi-extensions#3357]
- Tachiyomi version: 0.9.2
- Android version: 7.0

- Name: Tapas
- Extension version: 1.2.10

### Steps to reproduce:
1. Download any webtoon from Tapas
2. Update Tapas to latest version 

### Expected behavior
-"downloaded" should appear beside downloaded chapters in chapter list

-can open chapters even offline

### Actual behavior
-"downloaded" does not appear beside downloaded chapters in chapter list

-cannot open chapters even offline

### Other details
-download badges still appear as usual

-checking the directory via file manager, the chapters are there, just seems to not be read by the app

-problem seems to be arising from chapter names of all webtoons changing when extension is updated, as the chapters downloaded after update has a folder prefix "Episode # _ " whereas previously downloaded webtoons has none; chapter titles of all webtoons from tapas also reflect this change

-problem seems to be resolved by renaming the chapter folders from a file manager to reflect the format of the new chapter titles

**Comment by SnakeDoc83** [comment]
Tapas redesigned part of their website; so the part of the extension that parses chapter lists had to be rewritten for the most recent update. I could remove the "Episode #" from the chapter names but I don't know if that's enough to make chapter names match what they were and if they did it would break the downloads of chapters since the last update. My feeling is you just have to live with it.

**Comment by duckchomper** [comment]
I'm OK with the rename anyway, I'm just renaming all the folders manually. I hope though that Tapas doesn't do any more redesigning that would require a change in the extension, but I can't be too picky about that anyway.
