### ISSUE TITLE
MangaOwl not showing all available manga/manhwa

### ISSUE THREAD

**Issue by SneakyIntel** [inorichi/tachiyomi-extensions#3414]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10

### Source information
* Source name: MangaOwl
* Source extension version: 1.2.5

## Steps to reproduce
1. Go recent manga/manhwa using default view (ie: Till our Lips Touch)
2. Search manga/manhwa using webview

## Issue/Request
Unavailable manga/manhwa in both default & webview, but available when the site is opened on browser.

## Other details
![Screenshot_2020-06-06-01-48-50-70_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/66488632/83907446-ff19c280-a797-11ea-8072-510b30bdc63f.jpg)
![Screenshot_2020-06-06-01-49-06-70](https://user-images.githubusercontent.com/66488632/83907462-03de7680-a798-11ea-8b21-2b0d1e6e5785.jpg)

**Comment by SnakeDoc83** [comment]
So how'd you get to that page? It doesn't seem to show up when I use the site's search engine in Firefox; I had to use Google to actually find it.

**Comment by SneakyIntel** [comment]
Yes google chrome is my web browser for my phone and I use google as my main search engine.

**Comment by E3FxGaming** [comment]
For me it shows up when I search it on the website and when I search it with the MangaOwl Tachiyomi extension.

The website also has a banner "Server 1 problem was fixed. However, many side errors were left online. Please be patient and kindly report error if it's convenient to you." - maybe the problem you experienced had something to do with problems of the website?

Could someone else try to reproduce the problem?
If there is no way to reproduce it anymore there is nothing we can fix.

Oh and as a side note because I see the screenshot of the website: One of the features of Google AMP is a cache, so the problem could have been the website while the Google cache still had the old working search result. Anyone who wants to read about it can do so here https://developers.google.com/amp/cache/ .

**Comment by SnakeDoc83** [comment]
I feel like I've seen that "Server 1 problem was fixed" message up every time I check Manga Owl for a long time now, weeks if not months.

Manga Owl uses both .com and .net domains. Currently their site is forwarding to .net; so yeah, maybe something with their setup caused an issue where search results differ depending on the domain.'

**Comment by SneakyIntel** [comment]
Okay so I checked again, somehow it's okay now. I was able to find and download my manga with none of the aforementioned issues.
