### ISSUE TITLE
Mangadex Manga Status "Unknown" for many after newer update

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi-extensions#346]
I noticed a few of my manga had their status set to "Unknown" instead of Completed or Ongoing like they use to be after recently restoring the database onto this device with the newest dev version (r1418) and most current Mangadex extension (1.2.26)

I went onto my phone that had the newest dev version (r1418) but an older mangadex extension installed and the title when added showed as completed like it should. After updating, and removing/clearing database and readding that same title, the status shows as "Unknown" like on my main device.

The tested title in question was "Sakura Trick" if you want to try to reproduce it. It doesn't seem to affect everything.

**Comment by CarlosEsco** [comment]
This is correct. Extension was changed because completed on mangadex didn't mean it was completely scanned but that it was completed publishing. This caused an issue where a manga still be scanned would be ignored when updating non completed.  Now only manga that are completely scanned say completed

**Comment by BaronKrause** [comment]
Ha awesome! How does it tell now? If a manga lists completed but doesn't have a chapter with [END] it sets its status to unknown im assuming?

**Comment by CarlosEsco** [comment]
Json now has a last chapter number. If that's not 0 or blank then it's completed
