### ISSUE TITLE
[Bug] Kiryuu : image retry bug

### ISSUE THREAD

**Issue by Riztard** [inorichi/tachiyomi-extensions#3574]
### Device information
- Tachiyomi version: TachiJ2k
- Android version: 9 (pie)

### Source information
- Name: Kiryuu
- Extension version: Kiryuu 1.2.2
- Extension version: WP Mangastream 1.2.15

## Steps to reproduce
1. browse either kiryuu
2. search Tomb Raider King
3. download chapter 75

### Expected behavior
downloaded

### Actual behavior
always failed

### Other details
sometimes there is none sometime 1  sometime 2 
for example 2 here
![image](https://user-images.githubusercontent.com/16263232/85148232-18cc0700-b27a-11ea-8c37-178cec2741c5.png)

**Comment by SnakeDoc83** [comment]
As a point of information: this issue is slightly different from the one you linked in discord and the image you've posted here (which is from the old issue). The old issue was addressed by filtering out URLs containing "filerun" because they weren't valid images. This time, it's URLs containing "photothumb.db" that are causing the issue.
