### ISSUE TITLE
Webtoon results

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi-extensions#359]
Noticed something odd when searching for webtoons on the Line Webtoon extension and comparing it to results on the website.

There are some webtoons on the website that when searched show up as "Webtoon" like Orange Marmalade:
https://www.webtoons.com/search?keyword=orange%20marmalade
and it will show up in the results in Tachiyomi searches, but others like "My Succubus Girlfriend" show up under "Discover" when searched:
https://www.webtoons.com/search?keyword=my%20succubus%20girlfriend
Those are not available when searched in Tachiyomi.

I don't know what the distinction is or if there is even anything that can be done but I thought it was worth mentioning.

**Comment by daddydeadpool** [comment]
noticed the same thing while trying to add my succubus girlfriend, which was literally the entire reason I downloaded the webtoon addon.

**Comment by TonyToscana** [comment]
The discover search is fucked up, it shows the Chinese site's results insted of the English one. If no one fixes it I'll try to do it later.

**Comment by BaronKrause** [comment]
It works! Only issue I e found so far seems super minor, the ones that were only showing up under discover list their status as "Unknown", where the ones that were under webtion show the proper ongoing or completed.

**Comment by TonyToscana** [comment]
That's because the Discover webtoons don't have any status indicator (first image) meanwhile normal webtoons show if they're ongoing (second image) or have finished (third image)
![firefox_2018-06-13_14-19-28](https://user-images.githubusercontent.com/9658555/41350866-cf57e13e-6f14-11e8-8655-6b3552e19f6a.png)
![firefox_2018-06-13_14-20-46](https://user-images.githubusercontent.com/9658555/41350911-f9ba278e-6f14-11e8-9b3f-059f4e959fac.png)
![firefox_2018-06-13_14-21-00](https://user-images.githubusercontent.com/9658555/41350924-02f13234-6f15-11e8-8687-9ac4d6e41291.png)

**Comment by BaronKrause** [comment]
Ha! That explains that!

**Comment by CarlosEsco** [comment]
closing since search was changed
