### ISSUE TITLE
[Bug] nhentai: "Sort by" doesn't work

### ISSUE THREAD

**Issue by vengiare** [inorichi/tachiyomi-extensions#3617]
### Device information
- Tachiyomi version: Stable 0.9.2
- Android version: 9

### Source information
- Name: nhentai 1.2.25

### Other details
Selecting any sorting option doesn't work (it still sorts by *Popular: All time* unless you do a weird maneuver:

If you want to sort by *Recent* for example, you have to
- pick either *Popular: Today* or *Popular: Week*
- then pick *Recent*
- click [ Filter ] button

**Comment by baraa272** [comment]
Well apparently I don't want to open another issue about nhentai so here it is 
Issue : nhentai Id search DOWN 
So it Seems nhentai turned off thier id search off which make a bit of problem here since tachiyomi uses id search to get destination nhentai titles when opened or called by nhentai link 
And now it gives me blank page inside tachiyomi when it tries to parse nhentai link 
So if it appropriate maybe change the id search for this extension to parsing the (name) first then do the process of nhentai link?

**Comment by rama982** [comment]
Weird stuff, i can't reproduce the issue.
As when i trying all sort filter is working on my case.
flter > set sort by > search.

**Comment by vengiare** [comment]
It doesn't work **initially**, for me

open nhentai source > filters icon > sort by > any sorting other than *Popular: All time* > search

**Comment by rama982** [comment]
I do what you do, but in my case all sorting is working as intended on first try.
So i have no idea what the cause in your case.

**Comment by vengiare** [comment]
I don't really know what's causing it, and it happens on both stable and preview too. Hope others can test if it really is an isolated issue.

btw @baraa272 you ***should*** make a separate issue about your problem.

**Comment by DiabloPiotr** [comment]
Works fine for me. Tablet with android 8.1.0

**Comment by vengiare** [comment]
if it even is helpful:
Android version: 9
Device: Nokia TA-1053_00WW

I don't really know how but it happens consistently here. Tried in J2K and it worked fine.
