### ISSUE TITLE
[Bug] Mangasee mangalife date fix

### ISSUE THREAD

**Issue by CarlosEsco** [inorichi/tachiyomi-extensions#3778]
The chapter dates for these need to be the parsed differently.  I believe the local should be whatever the sites json is returning and not the default locale

For example mangalife chapter was uploaded at 10pm yesterday according to site . In app (j2k) it shows 7 hours ago.  So its -2 hours from east

User in Australia site shows 10pm yesterday also.  However in app it shows uploaded 22 hours ago.

Compared to a dex chapter both us and Australia shows uploaded 17 hours ago 

Now when it sorts. Est will show the correct order since the mangalife chapter is newer, Australia person will not

**Comment by SnakeDoc83** [comment]
As the code stands, it's only parsing the chapter date, not the time. When today's date of "7/13/2020" gets parsed, because there is no time information it's parsed as midnight (00:00:00) and so "x hours ago" in j2k equates to hours since local midnight. In this case, the source's JSON does include time information so this should be fixable but it illustrates that j2k assumes `date_upload` is always accurate to the hour when often the hour is a default of midnight, not an actual time reported by the source.
