### ISSUE TITLE
[Bug] <toonpoint >: <recaptcha not working in webview >

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#3780]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this 

### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: toonpoint
- Extension version: madara

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened
The web view should work properly
### Actual behavior
This happens instead
The recaptcha in not working 
### Other details
![Screenshot_20200713-202146_Tachiyomi](https://user-images.githubusercontent.com/57017947/87324888-2d827e80-c54a-11ea-963d-968313c2b9c4.jpg)

**Comment by fawadkhan121** [comment]
It gets stuck like in the picture and even the support team  is also getting this issue

**Comment by fawadkhan121** [comment]
Even if sometimes the recaptcha is done than when i close the app and open it again , it again asks for recaptcha and many times the recaptcha gets stuck and says checking browser

**Comment by fawadkhan121** [comment]
Manhwa 18 of fm reader extension is also doing the same thing it cannot bypass cloud flare and go to web view everytime

**Comment by fawadkhan121** [comment]
@SnakeDoc83

**Comment by SnakeDoc83** [comment]
I tested on my virtual device before adding and have tested on my physical device since it was merged--Cloudflare is passable. It can take a while for it to fully load (upwards of 20 seconds in some cases). If it doesn't load after a minute, click the "x" to close the webview and try again. Switching to the preview build of Tachiyomi may help. Also see general Cloudflare information in #3475. This is just how it is with Cloudflare especially since their switch to using hCaptcha.
