### ISSUE TITLE
[Bug] Dead / Broken sources

### ISSUE THREAD

**Issue by b1ackhand5** [inorichi/tachiyomi-extensions#3916]
I have gone through all my installed extensions sources and here is what I found:

FMReader - Comicastle - broken source, new site
FM Reader - readcomiconline.org - dead site

Madara - Happy Tea Scans - dead site
Madara - Manga Byte - site leads to kissmanga.in
Madara - Martial Scans - dead, webview leads to a news site
Madara - Teabeer Comics - webview works but site lock comics by the look of it.
Madara - Tritinia scans - webview work, source broken
Madara - Unknown Scans - dead site
Madara - Yo Manga - dead site

Paprika - MangaZuki.xyz - source broken, webview is fine

Gekan - One shot scans - dead site

**Comment by SnakeDoc83** [comment]
Some of these I won't remove right away--I know Martial Scans is supposedly coming back in a couple weeks and I've seen RCO come and go. The rest I'll slowly take care of.

**Comment by SnakeDoc83** [comment]
Everything but RCO has been addressed in one way or another. I'll remove them at some point if they don't come back.

**Comment by keinezeit8** [comment]
New dead sites:
Madara - Hero Manhua - timeout
Madara - Luxy Scans - down
Madara - NinjaScans - down
Genkan - Kraken Scans - Invalid SSL certificate

Any of those might still be up, especially Hero Manhua, since Hatigarm Scan (Genkan) and KKJ Scans (Genkan) also timeout but are back up sometimes. But I believe that Luxy- and NinjaScans both rebranded/merged into other groups.
