### ISSUE TITLE
Union Mangas not working

### ISSUE THREAD

**Issue by gabrielmartt** [inorichi/tachiyomi-extensions#392]
Union mangas, portuguese source not working

loading forever and error 504 appears

sorry about my english

Tachiyomi 7.4
union mangas 1.2.2

**Comment by masgritz** [comment]
The extension is fine, I even double checked for any changes in the structure (in case it needs to be updated) but the problem is their website itself.

Go to their http://unionmangas.site/ (if it's not down at the moment) and you'll see a message stating that they're going through a server maintenance:

"Atenção! Estamos realizando uma manutenção no servidor, por isso está ocorrendo toda essa instabilidade. Avisaremos quando terminar."

**Comment by CarlosEsco** [comment]
closing as its not a tachiyomi issue

**Comment by masgritz** [comment]
Just to add, Union Mangas has finished their server maintenance a few hours ago. Everything is back to normal.
