### ISSUE TITLE
turkish manga in batoto

### ISSUE THREAD

**Issue by opheliakc** [inorichi/tachiyomi-extensions#4]
Is it possible to have this?

**Comment by Horoneru** [comment]
Maybe by tweaking the previous code for batoto as an internal source in Tachiyomi ? [Here](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/source/online/english/Batoto.kt)
I don't know, Batoto isn't an extension anymore so it may be because logging in and/or its multiple languages sources could pose a problem

**Comment by inorichi** [comment]
Batoto isn't available because the API isn't ready for login yet. For now, only non-login sites can be implemented. I hope to support login and custom preferences in a future release.

**Comment by Horoneru** [comment]
I thought so. Thanks for clarifying !

**Comment by CarlosEsco** [comment]
Can you close Batoto is no more
