### ISSUE TITLE
[Meta] Move Jaminisbox from Foolslide to it's own extension, or add a new extension seperately from Foolslide.

### ISSUE THREAD

**Issue by gohanko** [inorichi/tachiyomi-extensions#4113]
##  Why/Project's Benefit/Existing Problem
Mainly because the extra sources in Foolslide clutters the extension menu. I only use it for Jaminisbox.

## Other Details
I can implement this, just want to gather opinions.

**Comment by CarlosEsco** [comment]
No

**Comment by gohanko** [comment]
@CarlosEsco Can you explain why not?

**Comment by CarlosEsco** [comment]
Not splitting out sources that are  part of a factory. Just so you can read the 4 manga left on JB

**Comment by gohanko** [comment]
@CarlosEsco That doesn't explain anything. Be more precise, is it because its sharing some code with other sources an you don't want duplication, or is it something else?

**Comment by CarlosEsco** [comment]
1.  Don't @  people unless there are multiple people in the conversation.  I already know you are talking to me.  
2.  For more explanation: There is no plans to duplicate code just to have extensions individualized.  We don't care about your specific usecase or complaints.  Making a new build.gradle file for each source in a multisouce and copying the code would not and will not be merged in.
3. you are welcome to fork this repo pull out JB and side load the extension yourself.  
4.  if you want to have a solution that would potentially be merged it would require the following:
     -   A way to generate an apk per a individual source from the multisources code and gradle file
     -  The above would not duplicate code, build.gradles etc  
     - You would also need to individually increment a sources version number without affecting the other in the multisource.
     -  Finally you would need to make sure its all backwards compatible and do this on every multisource available.

**Comment by gohanko** [comment]
Pardon me, I thought GitHub have notified you unless I @ you. Correct me if I'm wrong,

Extracting JB to it's own extension seems to fullfill 3 of the 4 conditions.

- You'd be generating a new extension apk
- We'll increment FoolSlide's version number, so that should be fine.
- It shouldn't really affect other sources (since it wouldn't make sense for other sources to depend on JB for some reason).

But for the duplicate code part, is the reason why all these sources are in FoolSlide is because they share similar URL structure? If so then extracting it would duplicate the code that builds the URL, and that is why it's not viable?

**Comment by CarlosEsco** [comment]
Being a contributor you get an email as well as if you comment on a thread it subscribes you by default.

And yes they all use the same backend which is why the are grouped in this case (https://foolcode.github.io/FoOlSlide/)
You can view the code here and see for the factories 
https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt


all use this one is used in one class
https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt

and one build.gradle that controls the versioning
https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/foolslide/build.gradle

**Comment by gohanko** [comment]
Ah, this makes so much more sense. Yeah, I agree we shouldn't separate them. Disabling the sources fixed the issue where it takes too long to load results as well.
