### ISSUE TITLE
[Bug] <Mangasee>: <Search/Browse function broken>

### ISSUE THREAD

**Issue by jinshelgeorge** [inorichi/tachiyomi-extensions#4177]
## Device information
- Tachiyomi version: 0.10.4 
- Android version: 8.0.0 (SDK 26)

## Source information
- Name: Mangasee
- Extension version: 1.2.12

## Steps to reproduce
1. Open Mangasee extension. 
2. Search your desired manga in the search box. 

### Expected behavior
The manga which you searched should show up in the results. 

### Actual behavior
The loading symbol keeps on loading and no results are loaded.

**Comment by SnakeDoc83** [comment]
MangaSee's implementation is a bit unique but it does make a network request and it seems to be working fine. I checked their website and read they had server issues around the time you posted this--so that was more than likely the issue.  Other than that, if you find the extension is being slow at times, can't really do anything about that.
