### ISSUE TITLE
MyMangaReaderCMS: duplicate FA scans source

### ISSUE THREAD

**Issue by yambadr** [inorichi/tachiyomi-extensions#480]
The latest updates made a duplicate Fallen Angels scans source. Please remove the 2nd one (the one w/o an extra space).

![screenshot_20180903-204236 2](https://user-images.githubusercontent.com/17810950/44999238-fe00a380-afbb-11e8-9e57-62c876cbd66e.png)

MyMangaReaderCMS 1.2.8
Tachiyomi 0.7.4
Android 8.1

**Comment by AmineI** [comment]
Since #474 [(see the diff)](https://github.com/inorichi/tachiyomi-extensions/commit/bbc1069945bfc48a02f79ccdf2ffc577efc0f595#diff-894f4bb43f1eefb45925e6914b35e2f9), "Fallen Angels Scans" has indeed been renamed to "Fallen AngelsScans".  (the former doesn't appear on my phone, probably you had some mangas saved before the name change)
But my update to MMRCMS afterwards kept this name. I can think of an easy fix (adding the space manually in the GeneratedSources file), but the issue will then come back on any subsequent update with GenSources.sh , which isn't desired.

Looks like the space was lost during the genSource.sh process, as it was split between two strings (MMRSource20 and MMRSource21), do you have any idea about that @null-dev ?

**Comment by yambadr** [comment]
It was originally w/o a space, then the 1.2.6 update added the space and made all my manga from that source to disappear. Now the space was removed again, so why was it added in the first place and why it's removed now?
