### ISSUE TITLE
[Bug] <BestManhua>: No Results Found

### ISSUE THREAD

**Issue by AsimpleGuy** [inorichi/tachiyomi-extensions#5018]
### Device information

Tachiyomi version: 0.10.5
Android version: 10
### Source information

Name: BestManhua (WP MangaStream)
Extension version: 1.2.38

### Expected behavior
Should show manga

### Actual behavior
No Result Found

**Comment by Riztard** [comment]
"Should show chapters" you mean manga? because i cant see the manga list
im pretty sure bestmanhua dindt use the same MangaStream with extension "MangaStream" but use similar name and look quite same, more like a knockoff. because need to change/add every selector because different class/id
[best manhua MangaStream](https://eastheme.com/products/mangastream-wordpress-theme/)
[ext wp mangastream](https://themesia.com/mangastream-wordpress-theme/)
so im not sure if i should combine the knockoff because same name and so other knockoff can be added to this factory, and i think only need to add all selector
