### ISSUE TITLE
[Bug] <Baca Manga>: <Can't get chapters>

### ISSUE THREAD

**Issue by HaruSasaki** [inorichi/tachiyomi-extensions#5036]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 8.1

## Source information
- Name: Baca Manga
- Extension version: 1.2.1

### Expected behavior
Chapter list showed

### Actual behavior
Show error message. Error message is:
"End of input at character 0 of"

## Other details
I recommend moving this to WP Mangastream.  Because in my opinion, this site uses WP Mangastream.

**Comment by Riztard** [comment]
the bug can be fixed by removing part that "Add date for latest chapter only" or move to wp mangastream.
but there is another bug in pageListParse (that i dont understand)
for anyone try to fix this

**Comment by antonycaporossi** [comment]
I'm working on this. They changed the way they load the date for the latest chapter (now is possibile also to load the date for every chapter) and the way they load the page list.
They use wp mangastream but the javascript code now is obfuscated and it's a pain to decode.

I found the string containing the pages but it is encoded in a different way than mangastream (this requires a separate extension) and I'm working on it because it contains two types of encoding.
