### ISSUE TITLE
Tachiyomi with extension closing when opening catalog

### ISSUE THREAD

**Issue by Biodam** [inorichi/tachiyomi-extensions#55]
Hello. Before anything I'm using:
Nexus 5x - Android 7.1.2
Tachiyomi 0.5.2
Android Studio 2.3.2
Tachiyomi-extensions commit: 7929a76

So, it is the first time for me building an Apk from Android studio. I downloaded the repository, opened it with Android Studio and did the "Build->Build APK". Opened the folder, copied the apk to my phone and installed it. It appears on my apps list:
![screenshot_20170530-221439](https://cloud.githubusercontent.com/assets/15266822/26611563/7f8f303a-4585-11e7-959f-5773d32b1023.png)

It appears on my "Sources" list inside Tachiyomi. But when I try to select it and select on my catalog the app just closes: [Video](https://youtu.be/4WMt4yKZ_70)

Then I tried to use logcat but this was what I got:
![image](https://cloud.githubusercontent.com/assets/15266822/26611493/0e21be2c-4585-11e7-8f17-b7585e404035.png)

Any idea of what I might be done wrong? Or if it is really a bug?

(Sorry about any weird english, I'm from Brazil.)

**Comment by null-dev** [comment]
The issue here is that you are using the E-Hentai source. The E-Hentai source actually requires a feature in Tachiyomi that **has not been released yet**.

The feature can be found in this commit: https://github.com/inorichi/tachiyomi/commit/b7b83305b2b67dd8c19d447f28ea58d5d93aa339.

If you would still like to use the E-Hentai source, you must download the latest dev build or wait for the next release of Tachiyomi.

**Comment by Biodam** [comment]
What a lucky of mine. My interest was on Sen Manga. And tried E-Hentai just to install another one.

Just uninstalled it, and installed "ReadComicOnline" to test another one. ReadComicOnline seens to work fine. But SenManga still closes the app for me when it is checked on Sources.

**Comment by null-dev** [comment]
Hmm, SenManga should not be crashing Tachiyomi. It would be awesome if you take the following steps to help me resolve this issue:

1. Open Tachiyomi and reproduce the crash (do whatever you did to make it crash).
2. **Immediately** after Tachiyomi crashes go to the `Settings` app on your phone, tap on `Developer options` and then tap on `Take bug report`.
3. If asked about the type of bug report, choose `Interactive report`.
4. Open the notification shade and wait for the bug report to complete. Once finished, tap on the notification to send it to me. You can upload it to Google Drive/whatever cloud service or you can email it to me at `contactnulldev@gmail.com`.

Thanks in advance for the help!

**Comment by Biodam** [comment]
Hey. Just sent it to your email. Check it out.
I'm the one that need to thank you for your patience and help!

**Comment by Biodam** [comment]
Just installed "it.mangaeden" to test another language, the catalog starts to populate then the app crashes. Maybe it is a language problem? Don't know just wondering.

**Comment by null-dev** [comment]
Alright, thanks for the bug report. I've finished reading though it and I've realized that I have actually seen this issue before.

It *appears* to be an issue with Kotlin, the programming language we are currently using. Unfortunately, the bad news is that although this issue is fixed in the latest version of Kotlin, Tachiyomi v0.5.2 isn't using the latest version of Kotlin yet (and hence does not contain the fix).

I think your only choice at this point would be to **use the dev build of Tachiyomi** if you would like to use these extensions right away, or **wait for the next release of Tachiyomi**.

I'll discuss this with inorichi a little bit more but I don't think anything will come out of it...

**Comment by Biodam** [comment]
Hey. Wow. No problem then.

I cloned the tachiyomi repository to make a new build to test out. But I'm getting this error:
![image](https://cloud.githubusercontent.com/assets/15266822/26613795/e77183e4-4592-11e7-8440-a8d5c71b8b98.png)

It's my first time using Android Studio, so if you can help me would be great! Sorry to bother you more.

**Comment by Biodam** [comment]
OMG. Sorry I've found. Read the comments is a good practice before posting here for help. Will continue to try to build here.

**Comment by Biodam** [comment]
Hey. Just to let you know that I've made the build with the last commit of Tachiyomi. And now Sen Manga is working and not closing the app anymore. 

Thank you so much for your help!
