### ISSUE TITLE
myreadingmanga doesn't load chapters

### ISSUE THREAD

**Issue by aurynluna** [inorichi/tachiyomi-extensions#566]
myreadingmanga is having issues again. I can't load any manga chapters, so it's impossible to read any manga there right now. I tried with several chapters and none of them load no matter how much time I wait. 

I'm using the most recent version for both the extension and the application.

**Comment by missimperfect** [comment]
I'm facing the same case as the original poster. In addition since it keeps on loading so I decided to download the chapter/s itself, but whenever I tried to download it it will show 'Chapter xx - Not used' and there will always be 2 pages left unable to complete the download. Ex: Chapter 1 has 15 pages, and the downloader will only download until 13 pages and stop downloading. Different problem but I thought maybe it has something to do with it. If moderator wants I can open another issue pages for this problem. Thank you.

**Comment by mll-Kerberos** [comment]
The problem with MyReadingManga has been fixed, you should be able to update the extension now, thanks for reporting the problem.
