### ISSUE TITLE
Fdroid Error

### ISSUE THREAD

**Issue by Sparh4wk** [inorichi/tachiyomi-extensions#65]
@j2ghz please can you fix fdroid repo if possible? Im geting this error today when I wanna install new catalogue.
![gdy6s5h](https://user-images.githubusercontent.com/7014826/27259821-10d17c0c-541c-11e7-82cf-17ecacaedc43.png)

I tested few devices and catalogues.

P.S. if possible can you accept my request on steam? ty

**Comment by j2ghz** [comment]
Really? I've been asking all my friends do you know sparhawk, he's sending me friend requests on steam, and I don't want to block him since it might be someone I know, but I won't add people I don't know.
What do you want to be friends on steam for?

Issue fixed: https://github.com/j2ghz/FDroid-Data/commit/d1a6a52187d7b3235a93f048fe60063569a8e4e8

**Comment by Sparh4wk** [comment]
Oh, sry... I didnt know that you are using steam as second facebook or something like that instead of being gaming and social platform... I was positive, that we can add each other, for maybe faster reporting or just for friendly talk about your repo, tachiyomi etc.. but as I can see that you have only 13 friends in FL on steam, you proly have your steams FL only for personal friends.. this was my mistake..  just ignore me and dont let this adding incident bother you... just wanted to add fellow countryman.

thanks for fixing repo
