### ISSUE TITLE
webtoon bug

### ISSUE THREAD

**Issue by 0lm** [inorichi/tachiyomi-extensions#737]
hi there. i noticed that somehow i cant browse in the webtoon catalogue. it always only lists te top 10 and i can only search. but i cant browse normally

**Comment by Vesnyx** [comment]
This is most likely because Webtoons doesn't have a page with all their webtoons listed. Instead, they have separated them into categories. If you can find a webpage that has everything listed, either by page or all-in-one, then I can try to add something in. Otherwise, there's no real way to add something like that.

**Comment by SnakeDoc83** [comment]
This could probably be consider a duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/458

One or both of these could probably be closed, there's no bug just a limitation due to the source's website design.
