### ISSUE TITLE
mangastream

### ISSUE THREAD

**Issue by ramenchef** [inorichi/tachiyomi-extensions#76]
English: https://readms.net

**Comment by TonyToscana** [comment]
I started doing this a while ago, but the problem is that mangastream doesn't have covers for the mangas and is really awkward browse mangas whithout cover (or the MS logo like I have it now). If this is not a problem I can finish it and make the PR.

**Comment by bbtora** [comment]
I think that should be fine as lone as we are getting to read the latest chapter as mangastream is one of the leading group in delivering scanlations of licensed titles. 

And it's a option for everyone whether they want to install this extension or not. 

For me, you should definitely go ahead :D

**Comment by TonyToscana** [comment]
Okay, I'm not at home so I'll try to finish it starting this thursday (13th). Shouldn't take long since I'm halfway done with it.

**Comment by TonyToscana** [comment]
I'm almost done with it, and I managed to put covers! I search the title on MAL and fetch the cover from there.

**Comment by TonyToscana** [comment]
I came up with an idea to make the search, and it seems to work pretty well. I'm almost ready to make the PR. Also noticed that the covers take a bit to load due to the calls it has to make to MAL, but it's something that only affect the first time that you access the source, since after that they are stored locally.
![player_2017-07-15_22-39-48](https://user-images.githubusercontent.com/9658555/28242537-047a48fa-69af-11e7-8414-a1c5695dbc24.png)
