### ISSUE TITLE
scan-fr

### ISSUE THREAD

**Issue by erwanoops** [inorichi/tachiyomi-extensions#782]
tachiyomi 0.8
MyMangaReaderCMS (scan-fr.io)

i can still browse manga list but i can get any chapter list (every one are empty)

**Comment by AmineI** [comment]
Yeah all these french sources changing everything for no reason are seriously bothering. Anyway, they renamed the class "chapters" into "chapterszz". Looks somewhat intentional to me. I may update it for now but if they do any more changes that looks like the purpose was to break compatibility, I won't play cat-and-mouse with them
