### ISSUE TITLE
Manga Plus extension marks "middle" chapters as new

### ISSUE THREAD

**Issue by ghost** [inorichi/tachiyomi-extensions#804]
Extension version: 1.2.1  
Tachiyomi version: r1463  

The middle 6 chapters near the paywalled ones keep getting marked as new, and is auto-downloaded according to my settings.

Screenshots:  
https://i.imgur.com/YJwRudS.png  
https://i.imgur.com/izwFtfY.png

**Comment by alessandrojean** [comment]
Unfortunately, I think there's nothing to fix on the extension side since this is the behavior of the source (to release the last chapters and the initial ones at the same time). I don't know how the "mark previous as read" feature is implemented, if it marks the number of the chapter and the chapters before this mark doesn't appear as new ones (even if new "middle" ones came up); or if it marks the chapters before individually and doesn't track the new "middle" ones (the behavior you talked about). What I can do is suggest that you create an issue in the Tachiyomi main repository explaining the behavior of the source and this bug caused by it, so they can do something to fix.

**Comment by metroid112** [comment]
Weird I'm not having this issue with the extension. I just marked them as read and they never appeared again
