### ISSUE TITLE
Hentai2Read - Search and filters are not working

### ISSUE THREAD

**Issue by Oxdeception** [inorichi/tachiyomi-extensions#89]
Tachiyomi version: 0.6.1-1197
Source version: 1.0.1
Android version: 4.4.2

Entering any text or changing any filters on this source returns the same results as directly visiting https://hentai2read.com/hentai-list/advanced-search/

**Comment by ddmgy** [comment]
Hi there, thanks for reporting this! I've fixed the issue with searching/filtering in my repo [here.](https://github.com/ddmgy/tachiyomi-extensions/tree/fix-hentai2read-search)

If it's not too much to ask, would you mind testing it before I open a pull request? It's working for me, but I want to make sure there are no further issues.

I've uploaded an APK with the changes [here](https://www.dropbox.com/s/p27lzjtqr68uoxj/tachiyomi-en.hentai2read-v1.0.1-debug.apk?dl=0), or you could build it for yourself if you don't trust an APK uploaded by a stranger (which I understand).

**Comment by Oxdeception** [comment]
Does appear to be working fine.
Beyond some spelling I found no issues. 
Sp - Notably the  "Charactor" textbox and "Collection of short stories/" tag.

**Comment by ddmgy** [comment]
Excellent. Thank you!

"Charactor" was a silly mistake, I'll correct it in my pull request.

As for the tag you mentioned, it is actually "Collection of Short Stories/Oneshots", but it gets cut off because it is too long. There are a few others like that, but there is nothing I can do because the drawer that holds the filters/tags is fixed-width.

**Comment by Oxdeception** [comment]
I figured that was what was happening, just that one tag stood out since it ends on the slash.
Thank you.
