### ISSUE TITLE
(Japscan) http error 404

### ISSUE THREAD

**Issue by demir923** [inorichi/tachiyomi-extensions#931]
Hi, I can't read anything from the source japscan. This is the only good French source... I update tachiyomi, clear cookies cache, reinstall the source, reboot... But still the same. The website is still working. Could you help me? Thanks again

**Comment by AmineI** [comment]
I just tried to refresh a japscan manga, received a 403 error (not 404), pressed "open in browser" ( in the "..." Menu on the top right of the info tab) and refreshed again - which worked.


> The only french source

Mangakawaii was recently added so you can try that in the meantime if you're still having issues.

**Comment by nicompo** [comment]
Hello, 
Same issue here. The catalogue has suddenly been reduced after installing the last version (tachiyomi 0.8.1, japscan 1.2.8). When I try to search a manga that was existing in the catalogue before the update (and still existing on the website), I get a 404 error.
Thanks in advance.

**Comment by Peuuuur-Noel** [comment]
403/503 seems to happens sometimes due to server or CloudFlare issue.
It works again after multiple tries or few minutes later (works as I write this comment).


> When I try to search a manga that was existing in the catalogue before the update (and still existing on the website), I get a 404 error.

The error 404 is due to this fix https://github.com/inorichi/tachiyomi-extensions/pull/891
Search request is in POST but intercepted by the code added for image discrambling and send again as GET.
GET request on the search URI (https://www.japscan.to/search/) send a 404 but return JSON on POST.

**Comment by DitFranXX** [comment]
Sorry, I didn't notice that search request uses `POST` method (I think all requests are use `GET`).

**Comment by demir923** [comment]
The website japscan.to looks down...

**Comment by AmineI** [comment]
Not on my end. Just tried, both website and extension working. Tried with another connection ?
________________________________
