### ISSUE TITLE
nHentai error 429

### ISSUE THREAD

**Issue by hakapoid** [inorichi/tachiyomi-extensions#938]
Tachiyomi version: 0.8.1
nHentai version: 1.2.6

Error is as stated in the title. Nothing loads when opening that source and that error prompt appears.

**Comment by CarlosEsco** [comment]
They are temp banning people who scrape. Someone will need to rework the extension

**Comment by hakapoid** [comment]
Alright then. Since its a known issue I hope it will be resolved soon :D

**Comment by az4521** [comment]
when you use the current useragent in the extension to send a request, it returns this
![image](https://user-images.githubusercontent.com/18432684/54654629-28680900-4a95-11e9-96d6-c7e2d27df6ce.png)

> Fix the Tachiyomi app and use an identifying user agent along with sane rate limits. Dozens of requests per second is going to get you permanently banned.

**Comment by nhentai** [comment]
Your extension immediately scrapes 26 pages when I tap on the "Latest" button. If I scroll down a few times, over 100 pages will be scraped in almost 30 seconds. You get IP banned because your extension ignores the multiple in-page warnings that ask you to stop sending so many requests.

The HTML you initially scrape contains more than enough information for you to render a card. Load the rest of the info when something's actually tapped.

You should not be sending more than one or two HTTP requests per tap. Until that's fixed, I will be blocking all requests sent by this extension. Also, add the version number to the user agent.

**Comment by arkon** [comment]
@nhentai 

> Your extension immediately scrapes 26 pages when I tap on the "Latest" button.

Do you mean the actual page and the 25 images? If not, I'm not really sure how it's scraping 26 pages.

> Also, add the version number to the user agent.

Of the app or the extension? We could probably do the extension version, if that's useful to you.

**Comment by az4521** [comment]
i think i know the issue and i'll be submitting the PR shortly
