### ISSUE TITLE
SSL hanshake error on MangaShow.Me 

### ISSUE THREAD

**Issue by ppp821203** [inorichi/tachiyomi-extensions#961]
tachiyomi (v.0.8.1)
MangaShow.Me (v.1.2.7) - korean

BUGS:
Yesterday, below error message displayed on screen.
I can't search catalog and download manga file.

Error Msg :
SSL handshake aborted : I/O during system call, connection reset by peer

**Comment by DitFranXX** [comment]
If you are lived in Korea, It caused by Korean Internet Censorship.
`Connection reset by peer` on Korean extensions are normally due to censorship.
(Technical Info: Sending `RST` Packet when detects censored-domain on SNI field during SSL handshake.)

`JMana` and `NewToki` will shows same error.

There's two solution in extension-side. One is Using IP without SSL(MSM only), Another one is wait for domain changes. (I'm not prefer to using IP address on side, it's more dangerous.)
Or trying to use VPN, proxy, or DPI-bypass tools on user-side.

**Comment by DitFranXX** [comment]
MSM v1.2.8 will fix this error. when it comes out, try it.

**Comment by DitFranXX** [comment]
Update: Starting v1.2.11 (#1061), Override BaseUrl setting has been added.
You can override baseurl on extension settings when site domain is changed. 
PS. Current baseurl is `https://manamoa3.net`
